use super::*;
use serde_json::json;
use std::fs;
use std::path::{Path, PathBuf};

fn temp_project(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("cowtext-taskctx-{tag}-{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    dir
}

fn touch(path: &Path, content: &str) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).unwrap();
    }
    fs::write(path, content).unwrap();
}

fn node(id: &str, title: &str, file_path: &str, pinned: bool) -> serde_json::Value {
    json!({
        "id": id, "title": title, "role": "reference", "brief": "",
        "filePath": file_path, "readOrder": 0, "pinned": pinned,
        "position": { "x": 0, "y": 0 }
    })
}

fn edge(id: &str, source: &str, target: &str, kind: &str) -> serde_json::Value {
    json!({ "id": id, "source": source, "target": target, "kind": kind })
}

fn graph_json(project_name: &str, nodes: &[serde_json::Value], edges: &[serde_json::Value]) -> String {
    json!({
        "version": 3, "projectName": project_name,
        "nodes": nodes, "edges": edges, "compileTargets": ["agents", "cursor"]
    })
    .to_string()
}

/// Writes `.cowtext/tasklinks.json` directly (taskctx.rs reads it via
/// `tasklinks::tasklinks_read`, so this helper has no dependency on
/// `tasklinks::tasklink_set`).
fn write_tasklinks(dir: &Path, links: &[serde_json::Value]) {
    let doc = json!({ "version": 1, "links": links });
    touch(
        &dir.join(".cowtext/tasklinks.json"),
        &serde_json::to_string_pretty(&doc).unwrap(),
    );
}

fn link(task_id: &str, node_ids: &[&str]) -> serde_json::Value {
    json!({ "taskId": task_id, "nodeIds": node_ids, "sessionIds": [] })
}

fn link_with_parent(task_id: &str, node_ids: &[&str], parent: &str) -> serde_json::Value {
    json!({ "taskId": task_id, "nodeIds": node_ids, "sessionIds": [], "parentTaskId": parent })
}

fn preview(root: &Path, task_id: &str, graph: &str) -> TaskContext {
    task_context_preview(root.to_string_lossy().into_owned(), task_id.to_string(), graph.to_string())
        .unwrap()
}

// ── Gate 8: golden file + closure semantics ────────────────────────────

/// A fixture graph: `rules` is globally pinned, `notes` is the task's own
/// seed (linked via `references` from `rules` so it renders visibly),
/// `imp` is transitively imported by `notes` (pulled into `node_ids` by the
/// closure even though `compile_preview`'s own renderer never surfaces a
/// non-pinned, non-referenced node in body text — §4.1 (node set) and §4.2
/// (rendered body) are deliberately not the same claim), and `extra` is
/// wired to nothing and must never appear.
fn golden_fixture(dir: &Path) -> String {
    touch(&dir.join("context/rules.md"), "rules body\n");
    touch(&dir.join("context/notes.md"), "notes body\n");
    touch(&dir.join("context/imp.md"), "imported body\n");
    touch(&dir.join("context/extra.md"), "extra body\n");
    write_tasklinks(dir, &[link("t-abc123", &["notes"])]);
    graph_json(
        "TestProj",
        &[
            node("rules", "Rules", "context/rules.md", true),
            node("notes", "Task Notes", "context/notes.md", false),
            node("imp", "Imported Detail", "context/imp.md", false),
            node("extra", "Unrelated", "context/extra.md", false),
        ],
        &[
            edge("e1", "rules", "notes", "references"),
            edge("e2", "notes", "imp", "imports"),
        ],
    )
}

#[test]
fn golden_task_context_body_and_node_ids_are_byte_exact() {
    let dir = temp_project("golden");
    let g = golden_fixture(&dir);

    let ctx = preview(&dir, "t-abc123", &g);

    assert!(ctx.errors.is_empty(), "unexpected errors: {:?}", ctx.errors);
    assert_eq!(ctx.node_ids, vec!["imp", "notes", "rules"]);
    let expected = "<!-- GENERATED BY COWTEXT — edit the graph or context/*.md, not this file -->\n\
\n\
# TestProj · task t-abc123 — agent context\n\
\n\
## Always read\n\
\n\
@context/rules.md\n\
\n\
## Read when relevant\n\
\n\
- When working on **Rules**, read @context/notes.md.\n";
    assert_eq!(ctx.body, expected);
    assert_eq!(ctx.bytes, expected.len());
    assert!(ctx.body.lines().next() == Some(crate::compile::GENERATED_HEADER));

    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn golden_task_context_is_deterministic_across_repeated_runs() {
    let dir = temp_project("golden-repeat");
    let g = golden_fixture(&dir);

    let first = preview(&dir, "t-abc123", &g);
    let second = preview(&dir, "t-abc123", &g);

    assert_eq!(first, second);
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn seeds_only_vs_seeds_plus_pinned_differ_exactly_by_pinned_nodes() {
    let dir = temp_project("seeds-vs-pinned");
    touch(&dir.join("context/seed.md"), "seed\n");
    touch(&dir.join("context/pin.md"), "pin\n");
    write_tasklinks(&dir, &[link("t-000001", &["seed"])]);

    let without_pin = graph_json(
        "P",
        &[
            node("seed", "Seed", "context/seed.md", false),
            node("pin", "Pin", "context/pin.md", false),
        ],
        &[],
    );
    let with_pin = graph_json(
        "P",
        &[
            node("seed", "Seed", "context/seed.md", false),
            node("pin", "Pin", "context/pin.md", true),
        ],
        &[],
    );

    let a = preview(&dir, "t-000001", &without_pin);
    let b = preview(&dir, "t-000001", &with_pin);

    assert_eq!(a.node_ids, vec!["seed"]);
    assert_eq!(b.node_ids, vec!["pin", "seed"]);
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn needs_dependency_nodes_never_leak_into_an_unrelated_tasks_context() {
    // taskctx never reads `depends_on`/`needs:` at all — this proves it by
    // construction: task B's nodes are linked to a *different* task (A),
    // and A's preview must never include them.
    let dir = temp_project("needs-absent");
    touch(&dir.join("context/a.md"), "a\n");
    touch(&dir.join("context/b.md"), "b\n");
    write_tasklinks(
        &dir,
        &[link("t-taska1", &["a"]), link("t-taskb1", &["b"])],
    );
    let g = graph_json(
        "P",
        &[
            node("a", "A", "context/a.md", false),
            node("b", "B", "context/b.md", false),
        ],
        &[],
    );

    let ctx = preview(&dir, "t-taska1", &g);
    assert_eq!(ctx.node_ids, vec!["a"]);
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn parent_ancestry_nodes_are_present() {
    let dir = temp_project("ancestry");
    touch(&dir.join("context/p.md"), "p\n");
    touch(&dir.join("context/c.md"), "c\n");
    write_tasklinks(
        &dir,
        &[
            link("t-parent", &["p"]),
            link_with_parent("t-child1", &["c"], "t-parent"),
        ],
    );
    let g = graph_json(
        "P",
        &[
            node("p", "Parent node", "context/p.md", false),
            node("c", "Child node", "context/c.md", false),
        ],
        &[],
    );

    let ctx = preview(&dir, "t-child1", &g);
    assert_eq!(ctx.node_ids, vec!["c", "p"]);
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn parent_cycle_is_reported_and_does_not_hang() {
    let dir = temp_project("cycle");
    write_tasklinks(
        &dir,
        &[
            link_with_parent("t-loopaa", &[], "t-loopbb"),
            link_with_parent("t-loopbb", &[], "t-loopaa"),
        ],
    );
    let g = graph_json("P", &[], &[]);

    let ctx = preview(&dir, "t-loopaa", &g);
    assert_eq!(ctx.node_ids, Vec::<String>::new());
    assert_eq!(ctx.body, "");
    assert_eq!(ctx.errors.len(), 1);
    match &ctx.errors[0] {
        TaskContextError::ParentCycle { path } => {
            assert_eq!(path.first(), path.last());
            assert!(path.contains(&"t-loopaa".to_string()));
            assert!(path.contains(&"t-loopbb".to_string()));
        }
        other => panic!("expected ParentCycle, got {other:?}"),
    }
    let _ = fs::remove_dir_all(&dir);
}

/// Regression for audit O3: `taskctx.rs` now delegates ancestry walking to
/// `tasklinks::ancestor_chain`, which reports exceeding the depth-8 cap as
/// `Err` (same shape as a genuine cycle) rather than silently truncating —
/// exactly §4.1's "depth cap 8; a cycle is a `ParentCycle` error, not a
/// silent truncation." Before the fix this case produced `errors == []`
/// with a 9-node, silently-truncated `node_ids`; it must now produce a
/// `ParentCycle` error and an empty context, matching `tasklink_set`'s
/// write-time refusal of the same shape.
#[test]
fn ancestry_depth_beyond_eight_generations_is_a_parent_cycle_error() {
    let dir = temp_project("deep-ancestry");
    // 10-generation chain t-gen000 -> t-gen001 -> ... -> t-gen009, no
    // actual repeated id anywhere in the chain — this is a depth-cap
    // overflow, not a literal cycle.
    let mut links = Vec::new();
    for i in 0..10 {
        let id = format!("t-gen{i:03}");
        let node_id = format!("g{i}");
        touch(&dir.join(format!("context/{node_id}.md")), "x\n");
        if i == 0 {
            links.push(link(&id, &[node_id.as_str()]));
        } else {
            let parent = format!("t-gen{:03}", i - 1);
            links.push(link_with_parent(&id, &[node_id.as_str()], &parent));
        }
    }
    write_tasklinks(&dir, &links);
    let nodes: Vec<serde_json::Value> = (0..10)
        .map(|i| node(&format!("g{i}"), &format!("G{i}"), &format!("context/g{i}.md"), false))
        .collect();
    let g = graph_json("P", &nodes, &[]);

    let ctx = preview(&dir, "t-gen009", &g);
    assert_eq!(ctx.node_ids, Vec::<String>::new());
    assert_eq!(ctx.body, "");
    assert_eq!(ctx.errors.len(), 1);
    match &ctx.errors[0] {
        TaskContextError::ParentCycle { path } => {
            assert!(path.contains(&"t-gen009".to_string()));
            // Depth cap 8 (audit F4 boundary fix, tasklinks.rs's
            // `ancestor_chain`): the walk gets exactly MAX_ANCESTRY_DEPTH+1
            // (9) iterations — enough to fully resolve an 8-hop chain *and*
            // confirm its root has no further parent. This fixture is 9
            // hops deep (t-gen009 -> ... -> t-gen000), one past the cap, so
            // the budget is exhausted exactly as the walk reaches the root
            // — the reported path runs all the way through t-gen000.
            assert!(path.contains(&"t-gen000".to_string()));
            assert_eq!(path.len(), 10, "task_id plus all 9 hops up to the root: {path:?}");
        }
        other => panic!("expected ParentCycle, got {other:?}"),
    }
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn ancestry_depth_of_exactly_eight_generations_resolves_without_error() {
    // Mirror of the test above at the other side of the boundary: a
    // 9-generation chain (8 real hops, t-gen008 -> ... -> t-gen000) must
    // resolve cleanly, not error — this pins the audit-F4 boundary fix
    // (tasklinks.rs's `ancestor_chain`, delegated to via O3) from
    // `task_context_preview`'s call site too, not just tasklinks.rs's own
    // unit tests.
    let dir = temp_project("eight-hop-ancestry");
    let mut links = Vec::new();
    for i in 0..9 {
        let id = format!("t-gen{i:03}");
        let node_id = format!("g{i}");
        touch(&dir.join(format!("context/{node_id}.md")), "x\n");
        if i == 0 {
            links.push(link(&id, &[node_id.as_str()]));
        } else {
            let parent = format!("t-gen{:03}", i - 1);
            links.push(link_with_parent(&id, &[node_id.as_str()], &parent));
        }
    }
    write_tasklinks(&dir, &links);
    let nodes: Vec<serde_json::Value> = (0..9)
        .map(|i| node(&format!("g{i}"), &format!("G{i}"), &format!("context/g{i}.md"), false))
        .collect();
    let g = graph_json("P", &nodes, &[]);

    let ctx = preview(&dir, "t-gen008", &g);
    assert_eq!(
        ctx.errors,
        Vec::<TaskContextError>::new(),
        "an exact 8-hop chain must not error: {:?}",
        ctx.errors
    );
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn task_with_no_linked_nodes_and_no_pinned_nodes_is_empty_subgraph() {
    let dir = temp_project("empty");
    write_tasklinks(&dir, &[]); // no entry at all for this task id
    let g = graph_json("P", &[node("x", "X", "context/x.md", false)], &[]);

    let ctx = preview(&dir, "t-nolink", &g);
    assert_eq!(ctx.node_ids, Vec::<String>::new());
    assert_eq!(ctx.body, "");
    assert_eq!(ctx.errors, vec![TaskContextError::EmptySubgraph]);
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn task_with_no_linked_nodes_but_a_pinned_node_still_compiles() {
    let dir = temp_project("empty-but-pinned");
    touch(&dir.join("context/pin.md"), "pin\n");
    write_tasklinks(&dir, &[]);
    let g = graph_json("P", &[node("pin", "Pin", "context/pin.md", true)], &[]);

    let ctx = preview(&dir, "t-nolink", &g);
    assert_eq!(ctx.node_ids, vec!["pin"]);
    assert!(ctx.errors.is_empty());
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn invalid_task_id_grammar_is_unknown_task_not_a_hard_error() {
    let dir = temp_project("bad-id");
    let g = graph_json("P", &[], &[]);

    let ctx = preview(&dir, "not-an-id", &g);
    assert_eq!(
        ctx.errors,
        vec![TaskContextError::UnknownTask {
            task_id: "not-an-id".to_string()
        }]
    );
    assert_eq!(ctx.node_ids, Vec::<String>::new());
    assert_eq!(ctx.body, "");
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn missing_backing_file_maps_to_missing_file_error() {
    let dir = temp_project("missing-file");
    // Node file is never created on disk.
    write_tasklinks(&dir, &[link("t-abc999", &["ghost"])]);
    let g = graph_json(
        "P",
        &[node("ghost", "Ghost", "context/ghost.md", false)],
        &[],
    );

    let ctx = preview(&dir, "t-abc999", &g);
    assert_eq!(ctx.node_ids, Vec::<String>::new());
    assert_eq!(ctx.body, "");
    match ctx.errors.as_slice() {
        [TaskContextError::MissingFile { node_id, file_path }] => {
            assert_eq!(node_id, "ghost");
            assert_eq!(file_path, "context/ghost.md");
        }
        other => panic!("expected one MissingFile error, got {other:?}"),
    }
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn claude_target_is_forced_regardless_of_the_projects_real_compile_targets() {
    // `golden_fixture`'s graph_json already sets compileTargets to
    // ["agents","cursor"] (no "claude") — a task context must still compile
    // successfully, proving the forced override.
    let dir = temp_project("forced-target");
    let g = golden_fixture(&dir);

    let ctx = preview(&dir, "t-abc123", &g);
    assert!(ctx.errors.is_empty());
    assert!(ctx.body.starts_with(crate::compile::GENERATED_HEADER));
    let _ = fs::remove_dir_all(&dir);
}

// ── Gate 9: allowlist disjointness, both directions ────────────────────

#[test]
fn task_context_write_rejects_a_path_traversal_task_id() {
    let dir = temp_project("write-traversal");
    let content = format!("{}\nbody\n", crate::compile::GENERATED_HEADER);

    let result = task_context_write(
        dir.to_string_lossy().into_owned(),
        "../../CLAUDE".to_string(),
        content,
    );
    assert!(result.is_err(), "expected Err, got {result:?}");
    assert!(!dir.join("CLAUDE.md").exists());
    assert!(!dir.parent().unwrap().join("CLAUDE.md").exists());
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn task_context_write_rejects_content_without_the_generated_header() {
    let dir = temp_project("write-no-header");
    let result = task_context_write(
        dir.to_string_lossy().into_owned(),
        "t-abc123".to_string(),
        "no header here\n".to_string(),
    );
    assert!(result.is_err(), "expected Err, got {result:?}");
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn task_context_write_rejects_a_malformed_task_id() {
    let dir = temp_project("write-bad-id");
    let content = format!("{}\nbody\n", crate::compile::GENERATED_HEADER);
    for bad in ["t-ABCDEF", "t-abcde", "t-abcdefg", "x-abcdef", "abcdef"] {
        let result = task_context_write(
            dir.to_string_lossy().into_owned(),
            bad.to_string(),
            content.clone(),
        );
        assert!(result.is_err(), "expected Err for {bad:?}, got {result:?}");
    }
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn task_context_write_succeeds_at_exactly_the_documented_path_and_is_idempotent() {
    let dir = temp_project("write-ok");
    let content = format!("{}\nbody\n", crate::compile::GENERATED_HEADER);

    let rel1 = task_context_write(
        dir.to_string_lossy().into_owned(),
        "t-abc123".to_string(),
        content.clone(),
    )
    .unwrap();
    assert_eq!(rel1, ".cowtext/context/task-t-abc123.md");
    let on_disk = fs::read_to_string(dir.join(&rel1)).unwrap();
    assert_eq!(on_disk, content);

    // Re-running produces byte-identical content (§4.5 "idempotent, deterministic").
    let rel2 = task_context_write(
        dir.to_string_lossy().into_owned(),
        "t-abc123".to_string(),
        content.clone(),
    )
    .unwrap();
    assert_eq!(rel2, rel1);
    assert_eq!(fs::read_to_string(dir.join(&rel2)).unwrap(), content);
    let _ = fs::remove_dir_all(&dir);
}

/// The other direction of Gate 9's disjointness: the injection path must
/// never be reachable through `compile_write`'s allowlist either.
#[test]
fn compile_write_refuses_the_task_context_shape() {
    let dir = temp_project("compile-write-refuses");
    fs::create_dir_all(&dir).unwrap();
    let content = format!("{}\nbody\n", crate::compile::GENERATED_HEADER);

    let result = crate::compile::compile_write(
        dir.to_string_lossy().into_owned(),
        vec![crate::compile::ApprovedFile {
            rel_path: ".cowtext/context/task-t-abc123.md".to_string(),
            content,
        }],
    );
    assert!(result.is_err(), "expected Err, got {result:?}");
    assert!(!dir.join(".cowtext/context/task-t-abc123.md").exists());
    let _ = fs::remove_dir_all(&dir);
}

/// And confirm the six real compile output shapes remain reachable through
/// `compile_write` — i.e. this test isn't passing because `compile_write`
/// rejects everything.
#[test]
fn compile_write_still_accepts_a_real_compile_output_shape() {
    let dir = temp_project("compile-write-accepts");
    fs::create_dir_all(&dir).unwrap();
    let content = format!("{}\nbody\n", crate::compile::GENERATED_HEADER);

    let result = crate::compile::compile_write(
        dir.to_string_lossy().into_owned(),
        vec![crate::compile::ApprovedFile {
            rel_path: "CLAUDE.md".to_string(),
            content,
        }],
    );
    assert_eq!(result.unwrap(), vec!["CLAUDE.md".to_string()]);
    assert!(dir.join("CLAUDE.md").is_file());
    let _ = fs::remove_dir_all(&dir);
}

// ── Misc infrastructure ─────────────────────────────────────────────────

#[test]
fn missing_tasklinks_file_reads_as_empty_not_an_error() {
    let dir = temp_project("no-sidecar");
    // No `.cowtext/tasklinks.json` written at all.
    touch(&dir.join("context/pin.md"), "pin\n");
    let g = graph_json("P", &[node("pin", "Pin", "context/pin.md", true)], &[]);

    let ctx = preview(&dir, "t-abc123", &g);
    assert!(ctx.errors.is_empty());
    assert_eq!(ctx.node_ids, vec!["pin"]);
    let _ = fs::remove_dir_all(&dir);
}

/// Regression for audit O2: unparseable (not even valid JSON)
/// `tasklinks.json` must degrade the same way `tasklinks::tasklinks_read`
/// degrades it everywhere else — `{version:1, links:[]}` — not surface a
/// raw `serde_json` parser message through `task_context_preview`'s
/// `errors`/`Err`. Before the fix this hard-`Err`ed with a string like
/// `"tasklinks.json: expected value at line 1 column 1"`.
#[test]
fn corrupt_tasklinks_json_degrades_to_empty_not_a_raw_parser_error() {
    let dir = temp_project("corrupt-sidecar");
    touch(&dir.join(".cowtext/tasklinks.json"), "not json at all{{{");
    touch(&dir.join("context/pin.md"), "pin\n");
    let g = graph_json("P", &[node("pin", "Pin", "context/pin.md", true)], &[]);

    let result = task_context_preview(
        dir.to_string_lossy().into_owned(),
        "t-abc123".to_string(),
        g,
    );
    let ctx = result.expect("corrupt tasklinks.json must degrade, not Err");
    assert!(ctx.errors.is_empty(), "unexpected errors: {:?}", ctx.errors);
    // Corrupt sidecar reads as if it had no links at all — only the
    // globally pinned node survives.
    assert_eq!(ctx.node_ids, vec!["pin"]);
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn tasklinks_version_greater_than_supported_is_a_hard_error() {
    let dir = temp_project("bad-version");
    touch(
        &dir.join(".cowtext/tasklinks.json"),
        r#"{"version":2,"links":[]}"#,
    );
    let g = graph_json("P", &[], &[]);

    let result = task_context_preview(
        dir.to_string_lossy().into_owned(),
        "t-abc123".to_string(),
        g,
    );
    assert!(result.is_err(), "expected Err, got {result:?}");
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn stale_seed_referencing_a_deleted_node_is_dropped_silently() {
    let dir = temp_project("stale-seed");
    touch(&dir.join("context/pin.md"), "pin\n");
    write_tasklinks(&dir, &[link("t-abc123", &["ghost-node-no-longer-exists"])]);
    let g = graph_json("P", &[node("pin", "Pin", "context/pin.md", true)], &[]);

    let ctx = preview(&dir, "t-abc123", &g);
    assert!(ctx.errors.is_empty());
    assert_eq!(ctx.node_ids, vec!["pin"]);
    let _ = fs::remove_dir_all(&dir);
}
