//! Compile: one graph snapshot → generated agent-context files (plan §5).
//! The webview sends the same serialized `graph.json` bytes that hit disk;
//! everything here is a pure function of that snapshot plus the node files
//! (plus an optional in-memory `overlay`, §10.1).
//!
//! Invariants this module owns:
//! - **Errors XOR files**: `compile_preview` returns validation errors or
//!   preview files, never both. Graph problems are data (`Ok` with errors);
//!   `Err` is reserved for infrastructure failure.
//! - **Deterministic output**: node order is Kahn's algorithm over the
//!   `imports`/`sequence`/`overrides` constraint graph, but only for the
//!   UNGUARDED subset — [`crate::project::edge_participates_in_order`]
//!   (WO13_CONTRACT.md §9) is the single predicate deciding participation,
//!   with `(readOrder, id)` as the ready-set tie-break, so the same graph
//!   always compiles to the same bytes. `references`/`contradicts`, and any
//!   GUARDED structural edge, never participate in ordering or cycle
//!   detection.
//! - **Five compile targets** (WO03): `claude` → `CLAUDE.md` (+
//!   `.claude/commands/*.md`, WO13 Amendment 1), `agents` → root/nested
//!   `AGENTS.md`, `cursor` → `.cursor/rules/*.mdc`, `copilot` →
//!   `.github/copilot-instructions.md`, `gemini` → `GEMINI.md`. All five
//!   share the same Kahn ordering and GENERATED header requirement; `claude`
//!   and `gemini` render `@path` inline imports, `agents` and `copilot`
//!   render plain markdown links (see [`LinkStyle`]).
//! - **`resolveLoad` is the only decider of load policy** (WO13_CONTRACT.md
//!   §8): every adapter below keys off [`crate::resolve_load::resolve_load`]
//!   (or, for `.cursor/rules` only, [`crate::resolve_load::resolve_load_ignoring_role_lock`]
//!   — §10.5, F11: Cursor has no invoke mechanism, so Amendment 1's
//!   destination lock must not reach it). `compile.rs` no longer computes
//!   its own pinned-closure; the old `effective_pinned` is gone.
//! - **Write allowlist**: `compile_write` only accepts the compile output
//!   shapes (`CLAUDE.md`, root or nested `AGENTS.md`, `.cursor/rules/*.mdc`,
//!   `.github/copilot-instructions.md`, `GEMINI.md`, one `.md` component
//!   under `.claude/agents/`, one `.md` component under
//!   `.claude/commands/`) and only content carrying the GENERATED header
//!   (agent files: the Cowtext context block markers instead — see below) —
//!   it must never become a general write primitive, even inside the path
//!   guard.
//! - **Agent context blocks**: independent of `compile_targets` and of the
//!   claude/agents/cursor adapters. Any node with role `agent` whose own
//!   file lives under `.claude/agents/` and has at least one outgoing
//!   `imports`/`references` edge gets a managed
//!   `<!-- COWTEXT CONTEXT START -->...<!-- COWTEXT CONTEXT END -->` block
//!   surgically written into (or appended onto) its own hand-written file —
//!   every other byte of that file is preserved. This is a ratified
//!   extension of "generated files carry the header": for these files the
//!   generated artifact is the block, not the file, so `handwritten` is
//!   always `false` and the write-allowlist accepts them without requiring
//!   `GENERATED_HEADER`.
//! - **Deprecated nodes are excluded from all compiled output** (§10.3):
//!   filtered at emission, never at ordering (a `sequence` edge through a
//!   deprecated node must not silently reorder the rest).

use crate::project::{checked_root, resolve_within_root, write_atomic};
use crate::resolve_load::{self, EdgeFacts, GuardKind, LoadEdgeKind, LoadRole, NodeFacts};
use serde::{Deserialize, Serialize};
use std::cmp::Reverse;
use std::collections::{BTreeMap, BinaryHeap, HashMap};
use std::fs;
use std::path::{Path, PathBuf};

/// First line of every generated file (`.mdc` and `.claude/commands/*.md`
/// carry it right after the frontmatter instead — both require `---` as
/// the first bytes).
pub const GENERATED_HEADER: &str =
    "<!-- GENERATED BY COWTEXT — edit the graph or context/*.md, not this file -->";

/// Delimiters of the managed context block surgically written into an
/// agent's own hand-written `.claude/agents/*.md` file (module doc).
pub const AGENT_BLOCK_START: &str =
    "<!-- COWTEXT CONTEXT START — generated from the graph; edit the graph, not this block -->";
pub const AGENT_BLOCK_END: &str = "<!-- COWTEXT CONTEXT END -->";

// ── Input model (tolerant subset of graph.json, v5, WO13_CONTRACT.md §4) ──

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct GraphIn {
    #[serde(default)]
    project_name: String,
    #[serde(default)]
    nodes: Vec<NodeIn>,
    #[serde(default)]
    edges: Vec<EdgeIn>,
    #[serde(default)]
    compile_targets: Vec<TargetIn>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct NodeIn {
    id: String,
    title: String,
    file_path: String,
    #[serde(default)]
    read_order: i64,
    /// v5: replaces `pinned: bool`. Absent ⇒ on-demand.
    #[serde(default)]
    root_load: Option<RootLoadIn>,
    #[serde(default)]
    role: RoleIn,
    /// Presence only matters — §10.3 excludes a deprecated node from every
    /// adapter regardless of what `replacedBy`/`since`/`reason` say.
    #[serde(default)]
    deprecated: Option<serde::de::IgnoredAny>,
}

impl NodeIn {
    fn is_deprecated(&self) -> bool {
        self.deprecated.is_some()
    }
}

#[derive(Deserialize, PartialEq, Clone, Copy)]
#[serde(rename_all = "lowercase")]
enum RootLoadIn {
    Always,
}

/// Only the roles compile cares about (§8.3's `LoadRole` split): `agent`
/// (context blocks), `command`/`skill` (Amendment 1's destination lock, via
/// [`crate::resolve_load`]); every other role parses fine as `Other`.
#[derive(Deserialize, PartialEq, Clone, Copy, Default)]
#[serde(rename_all = "lowercase")]
enum RoleIn {
    Agent,
    Command,
    Skill,
    #[serde(other)]
    #[default]
    Other,
}

impl RoleIn {
    fn is_agent(self) -> bool {
        matches!(self, RoleIn::Agent)
    }

    fn to_load_role(self) -> LoadRole {
        match self {
            RoleIn::Command => LoadRole::Command,
            RoleIn::Skill => LoadRole::Skill,
            RoleIn::Agent | RoleIn::Other => LoadRole::Other,
        }
    }
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct EdgeIn {
    id: String,
    source: String,
    target: String,
    kind: EdgeKindIn,
    /// v5: replaces `condition: Option<String>`.
    #[serde(default)]
    guard: Option<GuardIn>,
}

#[derive(Deserialize, Clone)]
#[serde(tag = "type", rename_all = "lowercase")]
enum GuardIn {
    Glob { globs: Vec<String> },
    Description { text: String },
}

#[derive(Deserialize, PartialEq, Clone, Copy)]
#[serde(rename_all = "kebab-case")]
enum EdgeKindIn {
    Imports,
    References,
    Overrides,
    Sequence,
    Contradicts,
    /// Future edge kinds parse fine and contribute nothing to compile.
    #[serde(other)]
    Unknown,
}

impl EdgeKindIn {
    fn name(self) -> &'static str {
        match self {
            EdgeKindIn::Imports => "imports",
            EdgeKindIn::References => "references",
            EdgeKindIn::Overrides => "overrides",
            EdgeKindIn::Sequence => "sequence",
            EdgeKindIn::Contradicts => "contradicts",
            EdgeKindIn::Unknown => "unknown",
        }
    }

}

#[derive(Deserialize, PartialEq, Clone, Copy)]
#[serde(rename_all = "lowercase")]
enum TargetIn {
    Claude,
    Agents,
    Cursor,
    /// WO03: `.github/copilot-instructions.md`, off by default.
    Copilot,
    /// WO03: `GEMINI.md` at the project root, off by default.
    Gemini,
    #[serde(other)]
    Unknown,
}

#[cfg(test)]
mod tests;

// ── Output model (camelCase on the wire) ──────────────────────────────

#[derive(Serialize, Debug)]
#[serde(rename_all = "camelCase")]
pub struct CompilePreview {
    /// Non-empty ⇒ `files` is empty. Validation errors and files never coexist.
    pub errors: Vec<ValidationError>,
    pub files: Vec<PreviewFile>,
}

#[derive(Serialize, Debug)]
#[serde(rename_all = "camelCase")]
pub struct PreviewFile {
    /// Forward-slash path relative to project root, e.g. ".cursor/rules/net.mdc".
    pub rel_path: String,
    /// "claude" | "agents" | "cursor" | "copilot" | "gemini" | "agent"
    pub target: String,
    /// None = file does not exist on disk yet (overlay never affects this — §10.1).
    pub old_content: Option<String>,
    pub new_content: String,
    /// Existing non-empty file lacking the GENERATED header — the UI must
    /// treat overwriting it as loud and opt-in.
    pub handwritten: bool,
    /// old_content == Some(new_content) byte-for-byte.
    pub unchanged: bool,
}

#[derive(Serialize, Debug)]
#[serde(rename_all = "camelCase")]
pub struct NodeRef {
    pub id: String,
    pub title: String,
}

#[derive(Serialize, Debug)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum ValidationError {
    /// Ordered cycle path; first node repeated as the last element.
    #[serde(rename_all = "camelCase")]
    Cycle { nodes: Vec<NodeRef> },
    #[serde(rename_all = "camelCase")]
    MissingFile {
        node_id: String,
        title: String,
        file_path: String,
    },
    /// Edge whose source or target id is not in nodes (tolerated parse, hard validation).
    #[serde(rename_all = "camelCase")]
    DanglingEdge {
        edge_id: String,
        edge_kind: String,
        missing_end: String,
    },
}

#[derive(Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ApprovedFile {
    pub rel_path: String,
    pub content: String,
}

// ── Commands ──────────────────────────────────────────────────────────

/// Validate the graph and render every requested target in memory.
/// `Err` only for infrastructure failure (bad root, unparseable JSON,
/// unreadable existing file); all graph problems come back as `errors`.
///
/// `overlay` (§10.1, WO13): in-memory `(relPath, content)` pairs that stand
/// in for files not yet on disk (or not yet saved with new content) — the
/// missing-file pass and every body-reading adapter consult it before disk.
/// `old_content`/`unchanged`/`handwritten` are NEVER affected: those compare
/// against on-disk truth only, which is the whole point of the step-4 diff.
#[tauri::command]
pub fn compile_preview(
    root: String,
    graph_json: String,
    overlay: Vec<ApprovedFile>,
) -> Result<CompilePreview, String> {
    let root_path = checked_root(&root)?;
    let graph: GraphIn =
        serde_json::from_str(&graph_json).map_err(|e| format!("graph.json: {e}"))?;

    let id_to_idx: HashMap<&str, usize> = graph
        .nodes
        .iter()
        .enumerate()
        .map(|(i, n)| (n.id.as_str(), i))
        .collect();

    // Overlay lookup keyed by resolved PathBuf (§10.1: "path equality is
    // decided by resolve_within_root(root, rel) returning equal PathBufs").
    let mut overlay_by_path: HashMap<PathBuf, &str> = HashMap::new();
    for f in &overlay {
        if let Ok(p) = resolve_within_root(&root_path, &f.rel_path) {
            overlay_by_path.insert(p, f.content.as_str());
        }
    }
    let read_file = |rel: &str| -> Result<String, String> {
        let p = resolve_within_root(&root_path, rel)?;
        if let Some(content) = overlay_by_path.get(&p) {
            return Ok((*content).to_string());
        }
        fs::read_to_string(&p).map_err(|e| format!("{rel}: {e}"))
    };

    let mut errors: Vec<ValidationError> = Vec::new();

    // Dangling edges (all kinds, Unknown included); dangling edges are
    // excluded from every later step.
    let mut live_edges: Vec<&EdgeIn> = Vec::new();
    for e in &graph.edges {
        let mut dangling = false;
        for end in [&e.source, &e.target] {
            if !id_to_idx.contains_key(end.as_str()) {
                dangling = true;
                errors.push(ValidationError::DanglingEdge {
                    edge_id: e.id.clone(),
                    edge_kind: e.kind.name().to_string(),
                    missing_end: end.clone(),
                });
            }
        }
        if !dangling {
            live_edges.push(e);
        }
    }

    // Missing files, reported in (readOrder, id) order. A node whose path
    // resolves to an overlay entry counts as present (§10.1).
    let mut by_read_order: Vec<&NodeIn> = graph.nodes.iter().collect();
    by_read_order.sort_by(|a, b| (a.read_order, &a.id).cmp(&(b.read_order, &b.id)));
    for n in by_read_order {
        let missing = match resolve_within_root(&root_path, &n.file_path) {
            Ok(p) => !p.is_file() && !overlay_by_path.contains_key(&p),
            Err(_) => true,
        };
        if missing {
            errors.push(ValidationError::MissingFile {
                node_id: n.id.clone(),
                title: n.title.clone(),
                file_path: n.file_path.clone(),
            });
        }
    }

    // Cycles + total order in one pass (the check IS the ordering).
    let order = match total_order(&graph.nodes, &live_edges, &id_to_idx) {
        Ok(order) => Some(order),
        Err(cycle) => {
            errors.push(ValidationError::Cycle { nodes: cycle });
            None
        }
    };

    if !errors.is_empty() {
        return Ok(CompilePreview {
            errors,
            files: Vec::new(),
        });
    }
    let order = order.expect("no errors implies a total order");

    let mut pos = vec![0usize; graph.nodes.len()];
    for (rank, &i) in order.iter().enumerate() {
        pos[i] = rank;
    }

    // §8: resolveLoad is the only decider. Build projected facts once and
    // resolve every node's Apply-mode policy up front — `emit_cursor` is the
    // ONLY caller of the Ignore-mode entry point (§8.3, §18.4 gate).
    let (node_facts, edge_facts) = to_load_facts(&graph.nodes, &live_edges);
    let loads: Vec<resolve_load::LoadResult> = graph
        .nodes
        .iter()
        .map(|n| resolve_load::resolve_load(&n.id, &node_facts, &edge_facts))
        .collect();
    let pinned: Vec<usize> = order
        .iter()
        .copied()
        .filter(|&i| loads[i].policy == resolve_load::ResolvedLoad::Always)
        .collect();

    let project_name = if graph.project_name.is_empty() {
        root_path
            .file_name()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| root.clone())
    } else {
        graph.project_name.clone()
    };

    let ctx = Ctx {
        project_name,
        nodes: &graph.nodes,
        pos,
        pinned,
        loads,
        node_facts,
        edge_facts,
        live_edges,
        id_to_idx,
        order,
    };

    // Adapters in fixed order; `contains` also dedups repeated targets.
    let wants = |t: TargetIn| graph.compile_targets.contains(&t);
    let mut produced: Vec<(String, &'static str, String)> = Vec::new();
    if wants(TargetIn::Claude) {
        produced.push((
            "CLAUDE.md".to_string(),
            "claude",
            ctx.emit_root(LinkStyle::AtImport),
        ));
        // §10.5, Amendment 1: `.claude/commands/*.md`, gated on `claude`
        // being a requested target — creating `.claude/` scaffolding in a
        // Cursor-only or Copilot-only project is exactly the unasked-for
        // write this app exists not to do.
        let mut commands = ctx.emit_commands(&read_file)?;
        commands.sort_by(|a, b| a.0.cmp(&b.0));
        for (rel, content) in commands {
            produced.push((rel, "claude", content));
        }
    }
    if wants(TargetIn::Agents) {
        produced.push((
            "AGENTS.md".to_string(),
            "agents",
            ctx.emit_root(LinkStyle::MarkdownLink),
        ));
        let mut nested = ctx.emit_nested_agents();
        nested.sort_by(|a, b| a.0.cmp(&b.0));
        for (rel, content) in nested {
            produced.push((rel, "agents", content));
        }
    }
    if wants(TargetIn::Cursor) {
        let mut mdc = ctx.emit_cursor(&read_file)?;
        mdc.sort_by(|a, b| a.0.cmp(&b.0));
        for (rel, content) in mdc {
            produced.push((rel, "cursor", content));
        }
    }
    if wants(TargetIn::Copilot) {
        produced.push((
            ".github/copilot-instructions.md".to_string(),
            "copilot",
            ctx.emit_root(LinkStyle::MarkdownLink),
        ));
    }
    if wants(TargetIn::Gemini) {
        produced.push((
            "GEMINI.md".to_string(),
            "gemini",
            ctx.emit_root(LinkStyle::AtImport),
        ));
    }

    let mut files = Vec::with_capacity(produced.len());
    for (rel_path, target, new_content) in produced {
        let path = resolve_within_root(&root_path, &rel_path)?;
        let old_content = if path.is_file() {
            Some(fs::read_to_string(&path).map_err(|e| format!("{rel_path}: {e}"))?)
        } else {
            None
        };
        let handwritten = match old_content.as_deref() {
            None => false,
            Some(c) => !c.trim().is_empty() && !has_header(c),
        };
        let unchanged = old_content.as_deref() == Some(new_content.as_str());
        files.push(PreviewFile {
            rel_path,
            target: target.to_string(),
            old_content,
            new_content,
            handwritten,
            unchanged,
        });
    }

    // Agent context blocks (module doc): independent of `compile_targets`.
    // Every non-deprecated node's file was already proven to exist above
    // (the missing-file pass walks all of `graph.nodes`), so reading it
    // here can only fail on a genuine infrastructure problem (permissions,
    // a mid-run deletion).
    for &i in &ctx.order {
        let n = &ctx.nodes[i];
        if n.is_deprecated() || !n.role.is_agent() || !is_agent_node_file(&n.file_path) {
            continue;
        }
        let mut target_ids: Vec<&str> = Vec::new();
        for e in &ctx.live_edges {
            if e.source == n.id
                && matches!(e.kind, EdgeKindIn::Imports | EdgeKindIn::References)
                && !ctx.node(&e.target).is_deprecated()
                && !target_ids.contains(&e.target.as_str())
            {
                target_ids.push(e.target.as_str());
            }
        }
        if target_ids.is_empty() {
            continue;
        }
        let mut targets: Vec<&NodeIn> = target_ids.iter().map(|id| ctx.node(id)).collect();
        targets.sort_by(|a, b| (a.read_order, &a.id).cmp(&(b.read_order, &b.id)));
        let lines: Vec<String> = targets.iter().map(|t| format!("@{}", t.file_path)).collect();

        let raw = read_file(&n.file_path)?;
        let new_content = merge_agent_block(&raw, &lines);
        // `old_content` for the diff is always the real on-disk bytes
        // (§10.1 — overlay never affects it), independent of what
        // `read_file` (overlay-aware) returned for the merge input above.
        let path = resolve_within_root(&root_path, &n.file_path)?;
        let disk_content =
            fs::read_to_string(&path).map_err(|e| format!("{}: {e}", n.file_path))?;
        let unchanged = disk_content == new_content;
        files.push(PreviewFile {
            rel_path: n.file_path.clone(),
            target: "agent".to_string(),
            old_content: Some(disk_content),
            new_content,
            handwritten: false,
            unchanged,
        });
    }

    Ok(CompilePreview {
        errors: Vec::new(),
        files,
    })
}

/// `true` iff `file_path` (forward or backward slashes, any case) names a
/// file directly under `.claude/agents/`.
fn is_agent_node_file(file_path: &str) -> bool {
    file_path
        .replace('\\', "/")
        .to_ascii_lowercase()
        .starts_with(".claude/agents/")
}

/// Surgically merge the managed `lines` (already `@path` formatted, in
/// final order) into `existing` file bytes. If both markers are present,
/// the span from the START marker's line through the END marker's line
/// (inclusive of the END line's own terminator) is replaced; every other
/// byte — prefix and suffix — is untouched. If absent, the block is
/// appended: a blank-line separator, the block, then a trailing newline.
fn merge_agent_block(existing: &str, lines: &[String]) -> String {
    let mut block = String::new();
    block.push_str(AGENT_BLOCK_START);
    for l in lines {
        block.push('\n');
        block.push_str(l);
    }
    block.push('\n');
    block.push_str(AGENT_BLOCK_END);

    if let (Some(start), Some(end)) = (existing.find(AGENT_BLOCK_START), existing.find(AGENT_BLOCK_END)) {
        if end >= start {
            let mut after = end + AGENT_BLOCK_END.len();
            if existing[after..].starts_with("\r\n") {
                after += 2;
            } else if existing[after..].starts_with('\n') {
                after += 1;
            }
            return format!("{}{}\n{}", &existing[..start], block, &existing[after..]);
        }
    }
    format!("{existing}\n{block}\n")
}

/// Write user-approved compile output. The UI enforces the diff-approval
/// trust boundary; this enforces the path boundary: allowlisted shapes only,
/// whole batch validated before any write. Every shape but the agent-context
/// one requires the GENERATED header; agent files require the Cowtext
/// context block markers instead (module doc: the generated artifact there
/// is the block, not the file).
#[tauri::command]
pub fn compile_write(root: String, files: Vec<ApprovedFile>) -> Result<Vec<String>, String> {
    let root_path = checked_root(&root)?;
    let mut resolved: Vec<(PathBuf, &ApprovedFile)> = Vec::with_capacity(files.len());
    for f in &files {
        let path = resolve_within_root(&root_path, &f.rel_path)?;
        let is_agent = match classify_output(&f.rel_path) {
            Some(is_agent) => is_agent,
            None => {
                return Err(format!(
                    "Refusing to write outside compile outputs: {}",
                    f.rel_path
                ))
            }
        };
        if is_agent {
            let has_markers =
                f.content.contains(AGENT_BLOCK_START) && f.content.contains(AGENT_BLOCK_END);
            if !has_markers {
                return Err(format!(
                    "Missing Cowtext context block markers: {}",
                    f.rel_path
                ));
            }
        } else if !has_header(&f.content) {
            return Err(format!("Missing GENERATED header: {}", f.rel_path));
        }
        resolved.push((path, f));
    }
    let mut written = Vec::with_capacity(resolved.len());
    for (path, f) in resolved {
        write_atomic(&path, &f.content)?;
        written.push(f.rel_path.clone());
    }
    Ok(written)
}

// ── Ordering + validation helpers ─────────────────────────────────────

/// Kahn's algorithm over the constraint graph: `sequence` says source
/// before target; `imports` and `overrides` (structural exactly like
/// `imports` — same direction, per contract) say target before source.
/// Participation is decided by [`crate::project::edge_participates_in_order`]
/// (WO13_CONTRACT.md §9: `kind.is_structural() && guard.is_none()`), never
/// re-derived inline — a GUARDED structural edge is conditional content,
/// exactly as the old `conditional` kind was, and must not enter ordering.
/// The ready set pops by `(readOrder, id)`, making manual order the
/// tie-break inside what topology allows. `Err` carries one concrete cycle
/// path, first node repeated as the last element.
fn total_order(
    nodes: &[NodeIn],
    edges: &[&EdgeIn],
    id_to_idx: &HashMap<&str, usize>,
) -> Result<Vec<usize>, Vec<NodeRef>> {
    let n = nodes.len();
    let mut indeg = vec![0usize; n];
    let mut succ: Vec<Vec<usize>> = vec![Vec::new(); n];
    let mut pred: Vec<Vec<usize>> = vec![Vec::new(); n];
    for e in edges {
        if !crate::project::edge_participates_in_order(
            to_project_kind(e.kind),
            e.guard.is_some(),
        ) {
            continue;
        }
        let s = id_to_idx[e.source.as_str()];
        let t = id_to_idx[e.target.as_str()];
        // Participation narrows `e.kind` to {Sequence, Imports, Overrides};
        // Sequence is source-before-target, the other two are
        // target-before-source.
        let (u, v) = if e.kind == EdgeKindIn::Sequence {
            (s, t)
        } else {
            (t, s)
        };
        succ[u].push(v);
        pred[v].push(u);
        indeg[v] += 1;
    }

    let mut ready = BinaryHeap::new();
    for (i, node) in nodes.iter().enumerate() {
        if indeg[i] == 0 {
            ready.push(Reverse((node.read_order, node.id.clone(), i)));
        }
    }
    let mut order = Vec::with_capacity(n);
    while let Some(Reverse((_, _, i))) = ready.pop() {
        order.push(i);
        for &v in &succ[i] {
            indeg[v] -= 1;
            if indeg[v] == 0 {
                ready.push(Reverse((nodes[v].read_order, nodes[v].id.clone(), v)));
            }
        }
    }
    if order.len() == n {
        Ok(order)
    } else {
        Err(find_cycle(nodes, &pred, &order))
    }
}

/// Maps this module's tolerant `EdgeKindIn` onto `project::EdgeKind` for
/// [`crate::project::edge_participates_in_order`]. `Unknown` has no
/// counterpart and is mapped to `References` — harmless, since
/// `is_structural()` is `false` for both, so the guard check never matters
/// for that arm.
fn to_project_kind(kind: EdgeKindIn) -> crate::project::EdgeKind {
    use crate::project::EdgeKind;
    match kind {
        EdgeKindIn::Imports => EdgeKind::Imports,
        EdgeKindIn::References | EdgeKindIn::Unknown => EdgeKind::References,
        EdgeKindIn::Overrides => EdgeKind::Overrides,
        EdgeKindIn::Sequence => EdgeKind::Sequence,
        EdgeKindIn::Contradicts => EdgeKind::Contradicts,
    }
}

/// The production projection from this module's tolerant `NodeIn`/`EdgeIn`
/// onto `resolve_load`'s decoupled `NodeFacts`/`EdgeFacts` (§8.3). Pulled
/// out to a standalone, independently testable function (audit D10:
/// "there are four hand-written projections... and a slip mapping
/// `overrides` → `Imports` in any of [them] would change compiled output
/// and pass the whole [resolve_load] corpus green" — that corpus only ever
/// exercised the test file's OWN parser, never this one). `edges` must
/// already be the dangling-filtered `live_edges` list; this function does
/// not re-check edge validity.
fn to_load_facts(nodes: &[NodeIn], edges: &[&EdgeIn]) -> (Vec<NodeFacts>, Vec<EdgeFacts>) {
    let node_facts = nodes
        .iter()
        .map(|n| NodeFacts {
            id: n.id.clone(),
            role: n.role.to_load_role(),
            root_always: n.root_load == Some(RootLoadIn::Always),
            deprecated: n.is_deprecated(),
        })
        .collect();
    let edge_facts = edges
        .iter()
        .map(|e| EdgeFacts {
            id: e.id.clone(),
            source: e.source.clone(),
            target: e.target.clone(),
            kind: match e.kind {
                EdgeKindIn::Imports => LoadEdgeKind::Imports,
                EdgeKindIn::References => LoadEdgeKind::References,
                _ => LoadEdgeKind::Other,
            },
            guard: match &e.guard {
                None => GuardKind::None,
                Some(GuardIn::Glob { .. }) => GuardKind::Glob,
                Some(GuardIn::Description { .. }) => GuardKind::Description,
            },
        })
        .collect();
    (node_facts, edge_facts)
}

/// Recover one concrete cycle from the residual constraint graph. Every
/// residual node kept a residual predecessor (its in-degree never reached
/// zero), so walking predecessors must revisit a node within n steps; the
/// revisited segment, reversed, is a forward cycle. Choices are made by
/// smallest node id so the report is deterministic.
fn find_cycle(nodes: &[NodeIn], pred: &[Vec<usize>], done: &[usize]) -> Vec<NodeRef> {
    let mut in_residual = vec![true; nodes.len()];
    for &i in done {
        in_residual[i] = false;
    }
    let start = (0..nodes.len())
        .filter(|&i| in_residual[i])
        .min_by(|&a, &b| nodes[a].id.cmp(&nodes[b].id))
        .expect("residual is non-empty when a cycle exists");
    let mut path = vec![start];
    loop {
        let cur = *path.last().expect("path never empty");
        let prev = pred[cur]
            .iter()
            .copied()
            .filter(|&p| in_residual[p])
            .min_by(|&a, &b| nodes[a].id.cmp(&nodes[b].id))
            .expect("residual nodes keep a residual predecessor");
        if let Some(hit) = path.iter().position(|&x| x == prev) {
            let mut cycle = vec![prev];
            cycle.extend(path[hit + 1..].iter().rev().copied());
            cycle.push(prev);
            return cycle
                .into_iter()
                .map(|i| NodeRef {
                    id: nodes[i].id.clone(),
                    title: nodes[i].title.clone(),
                })
                .collect();
        }
        path.push(prev);
    }
}

/// A clean folder glob is exactly `<dir>/**` where every `/`-separated
/// segment of `<dir>` is a plain path component: non-empty, not `.` or
/// `..`, and free of glob metacharacters, backslashes, and drive colons
/// (`src/net/**` → `src/net`; `src/net/**/*` is not clean and stays a root
/// bullet). Mirroring the `resolve_within_root` component walk here means a
/// clean dir can never alias another output path (`.` → root, `src/.` →
/// `src`) or escape the root (`../lib`) — dirty dirs simply stay root
/// bullets — and makes `dir.split('/').count()` the true directory depth
/// for the nested-file `../` link prefix.
fn clean_glob_dir(condition: &str) -> Option<&str> {
    let dir = condition.strip_suffix("/**")?;
    let clean = dir.split('/').all(|seg| {
        !seg.is_empty()
            && seg != "."
            && seg != ".."
            && !seg
                .chars()
                .any(|c| matches!(c, '*' | '?' | '[' | ']' | '\\' | ':'))
    });
    clean.then_some(dir)
}

/// Render a string as a YAML scalar for `.mdc`/command-file frontmatter.
/// Values that are safe as plain scalars (the common case — keeps output
/// byte-identical to the spec goldens) pass through untouched; anything that
/// would break or change meaning in plain style (`: `, leading indicator
/// chars, newlines, `null`/booleans, number-like strings — titles come from
/// hand-editable graph.json) is emitted as a double-quoted scalar with
/// escapes.
fn yaml_scalar(value: &str) -> String {
    const RESERVED: &[&str] = &[
        "~", "null", "Null", "NULL", "true", "True", "TRUE", "false", "False", "FALSE", "yes",
        "Yes", "YES", "no", "No", "NO", "on", "On", "ON", "off", "Off", "OFF",
    ];
    let plain_safe = !value.is_empty()
        && !RESERVED.contains(&value)
        && !value.starts_with(|c: char| {
            c.is_whitespace() || c.is_ascii_digit() || "-?:,[]{}#&*!|>'\"%@`+.".contains(c)
        })
        && !value.ends_with(|c: char| c.is_whitespace() || c == ':')
        && !value.contains(": ")
        && !value.contains(" #")
        && !value.chars().any(char::is_control);
    if plain_safe {
        return value.to_string();
    }
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// True when one of the first 10 trimmed lines equals the GENERATED header
/// (10 because `.mdc`/command files carry it after the frontmatter).
fn has_header(content: &str) -> bool {
    content.lines().take(10).any(|l| l.trim() == GENERATED_HEADER)
}

/// The shapes compile is allowed to write, and whether that shape is an
/// agent-context surgical edit (`Some(true)`) vs a normal fully-generated
/// file (`Some(false)`) — `None` means refuse. Exactly `CLAUDE.md`, any path
/// ending in `AGENTS.md`, one component under `.cursor/rules/` with an
/// `.mdc` extension, `.github/copilot-instructions.md` (that exact path
/// only — no nested variant), `GEMINI.md` at the project root only (no
/// nested variant), one `.md` component directly under `.claude/agents/`
/// (no nested subdirectory), or one `.md` component directly under
/// `.claude/commands/` (WO13 Amendment 1, §10.5 — same exact-shape rule, and
/// FULLY GENERATED, not surgical: a command file has no hand-authored
/// region to preserve). A strict allowlist, never a general write primitive
/// — every new shape is an exact-path or exact-shape match, not a
/// prefix/extension rule that could accidentally admit a near-miss.
/// **`.claude/skills/` is deliberately absent** (§10.6): that path is
/// CRUD-managed by `agents.rs` and compile must never write there.
///
/// WO13_AUDIT.md D9 (fix-round Stage 0): the ONE write allowlist — `pub(crate)`
/// so `import.rs` (the WO03-D2 importer guard) and `fsbatch.rs`
/// (`fs_apply_batch`'s one-writer guard, §12.1 rule 2/3) call this directly
/// instead of re-deriving their own copies. Do not let a third copy grow;
/// callers needing only "is this a compile-output shape at all" use
/// `classify_output(rel).is_some()`.
pub(crate) fn classify_output(rel: &str) -> Option<bool> {
    let norm = rel.replace('\\', "/");
    let parts: Vec<&str> = norm.split('/').filter(|p| !p.is_empty() && *p != ".").collect();
    match parts.as_slice() {
        [.., "AGENTS.md"] => Some(false),
        ["CLAUDE.md"] => Some(false),
        ["GEMINI.md"] => Some(false),
        [".github", "copilot-instructions.md"] => Some(false),
        [".cursor", "rules", name] => name
            .strip_suffix(".mdc")
            .is_some_and(|stem| !stem.is_empty())
            .then_some(false),
        [".claude", "agents", name] => name
            .to_ascii_lowercase()
            .strip_suffix(".md")
            .is_some_and(|stem| !stem.is_empty())
            .then_some(true),
        [".claude", "commands", name] => name
            .to_ascii_lowercase()
            .strip_suffix(".md")
            .is_some_and(|stem| !stem.is_empty())
            .then_some(false),
        _ => None,
    }
}

// ── Adapters ──────────────────────────────────────────────────────────

/// The two link syntaxes shared by [`Ctx::emit_root`]'s four root-file
/// adapters: `claude` and `gemini` both understand the `@path` inline-import
/// syntax (Claude Code and Gemini CLI share that context-file protocol);
/// `agents` and `copilot` are plain markdown with no import mechanism, so
/// they get ordinary links instead.
#[derive(Clone, Copy, PartialEq, Eq)]
enum LinkStyle {
    AtImport,
    MarkdownLink,
}

impl LinkStyle {
    /// A full "always read" list line for this node.
    fn pinned_line(self, n: &NodeIn) -> String {
        match self {
            LinkStyle::AtImport => format!("@{}", n.file_path),
            LinkStyle::MarkdownLink => format!("- [{}]({})", n.title, n.file_path),
        }
    }

    /// Just the reference fragment, for inlining into an
    /// [`Ctx::on_demand_bullets`] sentence (`"- When X, read {inline_link}."`).
    fn inline_link(self, n: &NodeIn) -> String {
        match self {
            LinkStyle::AtImport => format!("@{}", n.file_path),
            LinkStyle::MarkdownLink => format!("[{}]({})", n.title, n.file_path),
        }
    }
}

/// Everything the adapters read, built once after validation passes.
struct Ctx<'a> {
    project_name: String,
    nodes: &'a [NodeIn],
    /// Node indices in total order.
    order: Vec<usize>,
    /// node index → rank in `order`.
    pos: Vec<usize>,
    /// Node indices whose Apply-mode resolved policy is `Always`, in total order.
    pinned: Vec<usize>,
    /// node index → Apply-mode `resolveLoad` result (§8, computed once).
    loads: Vec<resolve_load::LoadResult>,
    /// Projected facts, kept around so `emit_cursor` can call the
    /// Ignore-mode entry point (its one sanctioned call site, §8.3).
    node_facts: Vec<NodeFacts>,
    edge_facts: Vec<EdgeFacts>,
    live_edges: Vec<&'a EdgeIn>,
    id_to_idx: HashMap<&'a str, usize>,
}

impl Ctx<'_> {
    fn node(&self, id: &str) -> &NodeIn {
        &self.nodes[self.id_to_idx[id]]
    }

    fn always(&self, idx: usize) -> bool {
        self.loads[idx].policy == resolve_load::ResolvedLoad::Always
    }

    /// Generated precedence markers (§10.4, E-C) for every `overrides` edge
    /// sourced at `source_idx` whose target is co-resident (both resolve to
    /// `always` — §11.1's definition, reused here). Sorted by edge id so
    /// output stays deterministic; recompiling twice reproduces the same
    /// bytes by construction (the whole root file is regenerated from
    /// scratch on every compile — no accumulation possible).
    fn precedence_markers(&self, source_idx: usize) -> Vec<String> {
        if !self.always(source_idx) {
            return Vec::new();
        }
        let source_id = self.nodes[source_idx].id.as_str();
        let mut markers: Vec<(&str, String)> = Vec::new();
        for e in &self.live_edges {
            if e.kind != EdgeKindIn::Overrides || e.source != source_id {
                continue;
            }
            let target_idx = self.id_to_idx[e.target.as_str()];
            if self.always(target_idx) {
                let target_title = &self.nodes[target_idx].title;
                markers.push((
                    e.id.as_str(),
                    format!(
                        "<!-- cowtext:precedence -->Takes precedence over \"{target_title}\" below."
                    ),
                ));
            }
        }
        markers.sort_by(|a, b| a.0.cmp(b.0));
        markers.into_iter().map(|(_, m)| m).collect()
    }

    /// On-demand bullets: `references` edges, and `imports` edges carrying a
    /// guard (glob or description — WO13 §10.2, the byte-identical
    /// replacement for the old `conditional` kind). Edge-driven, sorted by
    /// (compiled order of the target, edge id) — unaffected by Amendment 1's
    /// destination lock (§10.5: "rule 1 never suppresses an edge-driven
    /// bullet"). A deprecated target is skipped (§10.3: never appears in an
    /// on-demand bullet).
    fn on_demand_bullets(&self, link: &dyn Fn(&NodeIn) -> String) -> Vec<String> {
        let mut items: Vec<(usize, &str, String)> = Vec::new();
        for e in &self.live_edges {
            let target = self.node(&e.target);
            if target.is_deprecated() {
                continue;
            }
            let text = match (e.kind, &e.guard) {
                (EdgeKindIn::References, _) => format!(
                    "- When working on **{}**, read {}.",
                    self.node(&e.source).title,
                    link(target)
                ),
                (EdgeKindIn::Imports, Some(GuardIn::Glob { globs })) => {
                    format!("- When touching `{}`, read {}.", globs.join(","), link(target))
                }
                (EdgeKindIn::Imports, Some(GuardIn::Description { text })) => {
                    format!("- When {text}, read {}.", link(target))
                }
                _ => continue,
            };
            items.push((self.pos[self.id_to_idx[e.target.as_str()]], e.id.as_str(), text));
        }
        items.sort_by(|a, b| (a.0, a.1).cmp(&(b.0, b.1)));
        items.into_iter().map(|(_, _, text)| text).collect()
    }

    /// Root `CLAUDE.md` / `AGENTS.md` / `.github/copilot-instructions.md` /
    /// `GEMINI.md` — identical structure across all four targets, differing
    /// only in link syntax (`style`, see [`LinkStyle`]). Each pinned entry
    /// may be preceded by generated `overrides` precedence markers (§10.4).
    fn emit_root(&self, style: LinkStyle) -> String {
        let mut lines: Vec<String> = vec![
            GENERATED_HEADER.to_string(),
            String::new(),
            format!("# {} — agent context", self.project_name),
        ];
        if !self.pinned.is_empty() {
            lines.push(String::new());
            lines.push("## Always read".to_string());
            lines.push(String::new());
            for &i in &self.pinned {
                lines.extend(self.precedence_markers(i));
                lines.push(style.pinned_line(&self.nodes[i]));
            }
        }
        let bullets = self.on_demand_bullets(&|n: &NodeIn| style.inline_link(n));
        if !bullets.is_empty() {
            lines.push(String::new());
            lines.push("## Read when relevant".to_string());
            lines.push(String::new());
            lines.extend(bullets);
        }
        let mut out = lines.join("\n");
        out.push('\n');
        out
    }

    /// One `{dir}/AGENTS.md` per clean-folder-glob `imports` guard, one
    /// entry per glob string in each guard's `globs` array (§10.2: "one
    /// nested {dir}/AGENTS.md per clean folder glob, iterating each entry of
    /// a glob guard's globs"). These are an addition to the root bullets,
    /// not a move. A deprecated target is skipped (§10.3).
    fn emit_nested_agents(&self) -> Vec<(String, String)> {
        let mut by_dir: BTreeMap<&str, Vec<(&str, &str)>> = BTreeMap::new();
        for e in &self.live_edges {
            if e.kind != EdgeKindIn::Imports || self.node(&e.target).is_deprecated() {
                continue;
            }
            let Some(GuardIn::Glob { globs }) = &e.guard else {
                continue;
            };
            for g in globs {
                if let Some(dir) = clean_glob_dir(g) {
                    by_dir.entry(dir).or_default().push((e.id.as_str(), e.target.as_str()));
                }
            }
        }
        by_dir
            .into_iter()
            .map(|(dir, mut entries)| {
                entries.sort_by(|a, b| {
                    (self.pos[self.id_to_idx[a.1]], a.0).cmp(&(self.pos[self.id_to_idx[b.1]], b.0))
                });
                let prefix = "../".repeat(dir.split('/').count());
                let mut lines: Vec<String> = vec![
                    GENERATED_HEADER.to_string(),
                    String::new(),
                    format!("# {} — context for {}", self.project_name, dir),
                    String::new(),
                ];
                for (_, target_id) in entries {
                    let n = self.node(target_id);
                    lines.push(format!("- Read [{}]({}{}).", n.title, prefix, n.file_path));
                }
                let mut content = lines.join("\n");
                content.push('\n');
                (format!("{dir}/AGENTS.md"), content)
            })
            .collect()
    }

    /// `.claude/commands/*.md` (§10.5, Amendment 1): one file per node whose
    /// Apply-mode `resolveLoad` policy is `OnInvoke` — Amendment 1's rule 1,
    /// regardless of edges. Fully generated (not surgical): a command file
    /// has no hand-authored region owned by anything else, so an existing
    /// file lacking the GENERATED header is simply flagged `handwritten` by
    /// the existing trust boundary. `body` goes through the SAME
    /// overlay-aware `read_file` closure `emit_cursor` uses.
    fn emit_commands(
        &self,
        read_file: &dyn Fn(&str) -> Result<String, String>,
    ) -> Result<Vec<(String, String)>, String> {
        let mut stem_counts: HashMap<String, u32> = HashMap::new();
        let mut out = Vec::new();
        for &i in &self.order {
            let n = &self.nodes[i];
            if n.is_deprecated() {
                continue;
            }
            if self.loads[i].policy != resolve_load::ResolvedLoad::OnInvoke {
                continue;
            }
            let name = stem_for(&n.file_path, &n.id, &mut stem_counts);
            let raw = read_file(&n.file_path)?;
            let body = raw.replace("\r\n", "\n").replace('\r', "\n");
            let body = body.trim_end_matches('\n');
            let mut content = format!(
                "---\ndescription: {}\n---\n{}\n",
                yaml_scalar(&n.title),
                GENERATED_HEADER
            );
            if !body.is_empty() {
                content.push('\n');
                content.push_str(body);
                content.push('\n');
            }
            out.push((format!(".claude/commands/{name}.md"), content));
        }
        Ok(out)
    }

    /// `.cursor/rules/*.mdc` — one per node whose IGNORE-mode `resolveLoad`
    /// policy is `always` or `on-glob` (§10.5, F11: rule 1's destination
    /// lock does not reach Cursor — this is the one sanctioned call site for
    /// [`crate::resolve_load::resolve_load_ignoring_role_lock`]), in total
    /// order. `alwaysApply` wins over `globs`. Stale `.mdc` from earlier
    /// compiles are not deleted (out of scope). A deprecated node is
    /// skipped entirely.
    fn emit_cursor(
        &self,
        read_file: &dyn Fn(&str) -> Result<String, String>,
    ) -> Result<Vec<(String, String)>, String> {
        // node index → (edge_id, glob) pairs, in (edge_id, array-index) order.
        let mut globs: HashMap<usize, Vec<(&str, &str)>> = HashMap::new();
        for e in &self.live_edges {
            if e.kind != EdgeKindIn::Imports {
                continue;
            }
            let Some(GuardIn::Glob { globs: gs }) = &e.guard else {
                continue;
            };
            let t = self.id_to_idx[e.target.as_str()];
            for g in gs {
                globs.entry(t).or_default().push((e.id.as_str(), g.as_str()));
            }
        }
        for list in globs.values_mut() {
            // Stable sort by edge id only preserves each edge's own glob
            // array order among ties — exactly "(edge_id, index)".
            list.sort_by(|a, b| a.0.cmp(b.0));
        }

        let mut stem_counts: HashMap<String, u32> = HashMap::new();
        let mut out = Vec::new();
        for &i in &self.order {
            let n = &self.nodes[i];
            if n.is_deprecated() {
                continue;
            }
            let load = resolve_load::resolve_load_ignoring_role_lock(
                &n.id,
                &self.node_facts,
                &self.edge_facts,
            );
            let always = load.policy == resolve_load::ResolvedLoad::Always;
            let node_globs = globs.get(&i);
            if !always && node_globs.is_none() {
                continue;
            }
            let name = stem_for(&n.file_path, &n.id, &mut stem_counts);
            let rule_line = if always {
                "alwaysApply: true".to_string()
            } else {
                let joined = node_globs
                    .expect("non-always nodes reach here only as glob targets")
                    .iter()
                    .map(|(_, g)| *g)
                    .collect::<Vec<_>>()
                    .join(",");
                format!("globs: {}", yaml_scalar(&joined))
            };
            let raw = read_file(&n.file_path)?;
            let body = raw.replace("\r\n", "\n").replace('\r', "\n");
            let body = body.trim_end_matches('\n');
            let mut content = format!(
                "---\ndescription: {}\n{}\n---\n{}\n",
                yaml_scalar(&n.title),
                rule_line,
                GENERATED_HEADER
            );
            if !body.is_empty() {
                content.push('\n');
                content.push_str(body);
                content.push('\n');
            }
            out.push((format!(".cursor/rules/{name}.mdc"), content));
        }
        Ok(out)
    }
}

/// Shared stem-collision idiom for `emit_cursor`/`emit_commands` — but
/// **each caller passes its OWN `stem_counts` map** (F9: sharing one would
/// renumber unrelated nodes' `.mdc`/command-file names, a silent output
/// change §18.1 Part B row 5 exists to catch).
fn stem_for(file_path: &str, id: &str, stem_counts: &mut HashMap<String, u32>) -> String {
    let stem = Path::new(file_path)
        .file_stem()
        .map(|s| s.to_string_lossy().to_lowercase())
        .unwrap_or_else(|| id.to_lowercase());
    let count = stem_counts.entry(stem.clone()).and_modify(|c| *c += 1).or_insert(1);
    if *count == 1 {
        stem
    } else {
        format!("{stem}-{count}")
    }
}
