//! Compile: one graph snapshot → generated agent-context files (plan §5).
//! The webview sends the same serialized `graph.json` bytes that hit disk;
//! everything here is a pure function of that snapshot plus the node files.
//!
//! Invariants this module owns:
//! - **Errors XOR files**: `compile_preview` returns validation errors or
//!   preview files, never both. Graph problems are data (`Ok` with errors);
//!   `Err` is reserved for infrastructure failure.
//! - **Deterministic output**: node order is Kahn's algorithm over the
//!   `imports`/`sequence` constraint graph with `(readOrder, id)` as the
//!   ready-set tie-break, so the same graph always compiles to the same bytes.
//! - **Write allowlist**: `compile_write` only accepts the compile output
//!   shapes (`CLAUDE.md`, root or nested `AGENTS.md`, `.cursor/rules/*.mdc`)
//!   and only content carrying the GENERATED header — it must never become a
//!   general write primitive, even inside the path guard.

use crate::project::{checked_root, resolve_within_root, write_atomic};
use serde::{Deserialize, Serialize};
use std::cmp::Reverse;
use std::collections::{BTreeMap, BinaryHeap, HashMap};
use std::fs;
use std::path::{Path, PathBuf};

/// First line of every generated file (`.mdc` carries it right after the
/// frontmatter instead — Cursor requires `---` as the first bytes).
pub const GENERATED_HEADER: &str =
    "<!-- GENERATED BY COWTEXT — edit the graph or context/*.md, not this file -->";

// ── Input model (tolerant subset of graph.json, plan §4) ──────────────

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct GraphIn {
    #[serde(default)]
    project_name: String,
    #[serde(default)]
    nodes: Vec<NodeIn>,
    #[serde(default)]
    edges: Vec<EdgeIn>,
    #[serde(default)]
    compile_targets: Vec<TargetIn>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct NodeIn {
    id: String,
    title: String,
    file_path: String,
    #[serde(default)]
    read_order: i64,
    #[serde(default)]
    pinned: bool,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct EdgeIn {
    id: String,
    source: String,
    target: String,
    kind: EdgeKindIn,
    #[serde(default)]
    condition: Option<String>,
}

#[derive(Deserialize, PartialEq, Clone, Copy)]
#[serde(rename_all = "lowercase")]
enum EdgeKindIn {
    Imports,
    References,
    Conditional,
    Sequence,
    /// Future edge kinds parse fine and contribute nothing to compile.
    #[serde(other)]
    Unknown,
}

impl EdgeKindIn {
    fn name(self) -> &'static str {
        match self {
            EdgeKindIn::Imports => "imports",
            EdgeKindIn::References => "references",
            EdgeKindIn::Conditional => "conditional",
            EdgeKindIn::Sequence => "sequence",
            EdgeKindIn::Unknown => "unknown",
        }
    }
}

#[derive(Deserialize, PartialEq, Clone, Copy)]
#[serde(rename_all = "lowercase")]
enum TargetIn {
    Claude,
    Agents,
    Cursor,
    #[serde(other)]
    Unknown,
}

// ── Output model (camelCase on the wire) ──────────────────────────────

#[derive(Serialize, Debug)]
#[serde(rename_all = "camelCase")]
pub struct CompilePreview {
    /// Non-empty ⇒ `files` is empty. Validation errors and files never coexist.
    pub errors: Vec<ValidationError>,
    pub files: Vec<PreviewFile>,
}

#[derive(Serialize, Debug)]
#[serde(rename_all = "camelCase")]
pub struct PreviewFile {
    /// Forward-slash path relative to project root, e.g. ".cursor/rules/net.mdc".
    pub rel_path: String,
    /// "claude" | "agents" | "cursor"
    pub target: String,
    /// None = file does not exist on disk yet.
    pub old_content: Option<String>,
    pub new_content: String,
    /// Existing non-empty file lacking the GENERATED header — the UI must
    /// treat overwriting it as loud and opt-in.
    pub handwritten: bool,
    /// old_content == Some(new_content) byte-for-byte.
    pub unchanged: bool,
}

#[derive(Serialize, Debug)]
#[serde(rename_all = "camelCase")]
pub struct NodeRef {
    pub id: String,
    pub title: String,
}

#[derive(Serialize, Debug)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum ValidationError {
    /// Ordered cycle path; first node repeated as the last element.
    #[serde(rename_all = "camelCase")]
    Cycle { nodes: Vec<NodeRef> },
    #[serde(rename_all = "camelCase")]
    MissingFile {
        node_id: String,
        title: String,
        file_path: String,
    },
    /// Edge whose source or target id is not in nodes (tolerated parse, hard validation).
    #[serde(rename_all = "camelCase")]
    DanglingEdge {
        edge_id: String,
        edge_kind: String,
        missing_end: String,
    },
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApprovedFile {
    pub rel_path: String,
    pub content: String,
}

// ── Commands ──────────────────────────────────────────────────────────

/// Validate the graph and render every requested target in memory.
/// `Err` only for infrastructure failure (bad root, unparseable JSON,
/// unreadable existing file); all graph problems come back as `errors`.
#[tauri::command]
pub fn compile_preview(root: String, graph_json: String) -> Result<CompilePreview, String> {
    let root_path = checked_root(&root)?;
    let graph: GraphIn =
        serde_json::from_str(&graph_json).map_err(|e| format!("graph.json: {e}"))?;

    let id_to_idx: HashMap<&str, usize> = graph
        .nodes
        .iter()
        .enumerate()
        .map(|(i, n)| (n.id.as_str(), i))
        .collect();

    let mut errors: Vec<ValidationError> = Vec::new();

    // Dangling edges (all kinds, Unknown included); dangling edges are
    // excluded from every later step.
    let mut live_edges: Vec<&EdgeIn> = Vec::new();
    for e in &graph.edges {
        let mut dangling = false;
        for end in [&e.source, &e.target] {
            if !id_to_idx.contains_key(end.as_str()) {
                dangling = true;
                errors.push(ValidationError::DanglingEdge {
                    edge_id: e.id.clone(),
                    edge_kind: e.kind.name().to_string(),
                    missing_end: end.clone(),
                });
            }
        }
        if !dangling {
            live_edges.push(e);
        }
    }

    // Missing files, reported in (readOrder, id) order.
    let mut by_read_order: Vec<&NodeIn> = graph.nodes.iter().collect();
    by_read_order.sort_by(|a, b| (a.read_order, &a.id).cmp(&(b.read_order, &b.id)));
    for n in by_read_order {
        let missing = match resolve_within_root(&root_path, &n.file_path) {
            Ok(p) => !p.is_file(),
            Err(_) => true,
        };
        if missing {
            errors.push(ValidationError::MissingFile {
                node_id: n.id.clone(),
                title: n.title.clone(),
                file_path: n.file_path.clone(),
            });
        }
    }

    // Cycles + total order in one pass (the check IS the ordering).
    let order = match total_order(&graph.nodes, &live_edges, &id_to_idx) {
        Ok(order) => Some(order),
        Err(cycle) => {
            errors.push(ValidationError::Cycle { nodes: cycle });
            None
        }
    };

    if !errors.is_empty() {
        return Ok(CompilePreview {
            errors,
            files: Vec::new(),
        });
    }
    let order = order.expect("no errors implies a total order");

    let mut pos = vec![0usize; graph.nodes.len()];
    for (rank, &i) in order.iter().enumerate() {
        pos[i] = rank;
    }
    let pinned_set = effective_pinned(&graph.nodes, &live_edges, &id_to_idx);
    let pinned: Vec<usize> = order.iter().copied().filter(|&i| pinned_set[i]).collect();

    let project_name = if graph.project_name.is_empty() {
        root_path
            .file_name()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| root.clone())
    } else {
        graph.project_name.clone()
    };

    let ctx = Ctx {
        project_name,
        nodes: &graph.nodes,
        pos,
        pinned,
        pinned_set,
        live_edges,
        id_to_idx,
        order,
    };

    // Adapters in fixed order; `contains` also dedups repeated targets.
    let wants = |t: TargetIn| graph.compile_targets.contains(&t);
    let mut produced: Vec<(String, &'static str, String)> = Vec::new();
    if wants(TargetIn::Claude) {
        produced.push(("CLAUDE.md".to_string(), "claude", ctx.emit_root(true)));
    }
    if wants(TargetIn::Agents) {
        produced.push(("AGENTS.md".to_string(), "agents", ctx.emit_root(false)));
        let mut nested = ctx.emit_nested_agents();
        nested.sort_by(|a, b| a.0.cmp(&b.0));
        for (rel, content) in nested {
            produced.push((rel, "agents", content));
        }
    }
    if wants(TargetIn::Cursor) {
        let read_file = |rel: &str| -> Result<String, String> {
            let p = resolve_within_root(&root_path, rel)?;
            fs::read_to_string(&p).map_err(|e| format!("{rel}: {e}"))
        };
        let mut mdc = ctx.emit_cursor(&read_file)?;
        mdc.sort_by(|a, b| a.0.cmp(&b.0));
        for (rel, content) in mdc {
            produced.push((rel, "cursor", content));
        }
    }

    let mut files = Vec::with_capacity(produced.len());
    for (rel_path, target, new_content) in produced {
        let path = resolve_within_root(&root_path, &rel_path)?;
        let old_content = if path.is_file() {
            Some(fs::read_to_string(&path).map_err(|e| format!("{rel_path}: {e}"))?)
        } else {
            None
        };
        let handwritten = match old_content.as_deref() {
            None => false,
            Some(c) => !c.trim().is_empty() && !has_header(c),
        };
        let unchanged = old_content.as_deref() == Some(new_content.as_str());
        files.push(PreviewFile {
            rel_path,
            target: target.to_string(),
            old_content,
            new_content,
            handwritten,
            unchanged,
        });
    }

    Ok(CompilePreview {
        errors: Vec::new(),
        files,
    })
}

/// Write user-approved compile output. The UI enforces the diff-approval
/// trust boundary; this enforces the path boundary: allowlisted shapes only,
/// GENERATED header required, whole batch validated before any write.
#[tauri::command]
pub fn compile_write(root: String, files: Vec<ApprovedFile>) -> Result<Vec<String>, String> {
    let root_path = checked_root(&root)?;
    let mut resolved: Vec<(PathBuf, &ApprovedFile)> = Vec::with_capacity(files.len());
    for f in &files {
        let path = resolve_within_root(&root_path, &f.rel_path)?;
        if !is_allowed_output(&f.rel_path) {
            return Err(format!(
                "Refusing to write outside compile outputs: {}",
                f.rel_path
            ));
        }
        if !has_header(&f.content) {
            return Err(format!("Missing GENERATED header: {}", f.rel_path));
        }
        resolved.push((path, f));
    }
    let mut written = Vec::with_capacity(resolved.len());
    for (path, f) in resolved {
        write_atomic(&path, &f.content)?;
        written.push(f.rel_path.clone());
    }
    Ok(written)
}

// ── Ordering + validation helpers ─────────────────────────────────────

/// Kahn's algorithm over the constraint graph: `sequence` says source
/// before target, `imports` says target before source. The ready set pops
/// by `(readOrder, id)`, making manual order the tie-break inside what
/// topology allows. `Err` carries one concrete cycle path, first node
/// repeated as the last element.
fn total_order(
    nodes: &[NodeIn],
    edges: &[&EdgeIn],
    id_to_idx: &HashMap<&str, usize>,
) -> Result<Vec<usize>, Vec<NodeRef>> {
    let n = nodes.len();
    let mut indeg = vec![0usize; n];
    let mut succ: Vec<Vec<usize>> = vec![Vec::new(); n];
    let mut pred: Vec<Vec<usize>> = vec![Vec::new(); n];
    for e in edges {
        let s = id_to_idx[e.source.as_str()];
        let t = id_to_idx[e.target.as_str()];
        let (u, v) = match e.kind {
            EdgeKindIn::Sequence => (s, t),
            EdgeKindIn::Imports => (t, s),
            _ => continue,
        };
        succ[u].push(v);
        pred[v].push(u);
        indeg[v] += 1;
    }

    let mut ready = BinaryHeap::new();
    for (i, node) in nodes.iter().enumerate() {
        if indeg[i] == 0 {
            ready.push(Reverse((node.read_order, node.id.clone(), i)));
        }
    }
    let mut order = Vec::with_capacity(n);
    while let Some(Reverse((_, _, i))) = ready.pop() {
        order.push(i);
        for &v in &succ[i] {
            indeg[v] -= 1;
            if indeg[v] == 0 {
                ready.push(Reverse((nodes[v].read_order, nodes[v].id.clone(), v)));
            }
        }
    }
    if order.len() == n {
        Ok(order)
    } else {
        Err(find_cycle(nodes, &pred, &order))
    }
}

/// Recover one concrete cycle from the residual constraint graph. Every
/// residual node kept a residual predecessor (its in-degree never reached
/// zero), so walking predecessors must revisit a node within n steps; the
/// revisited segment, reversed, is a forward cycle. Choices are made by
/// smallest node id so the report is deterministic.
fn find_cycle(nodes: &[NodeIn], pred: &[Vec<usize>], done: &[usize]) -> Vec<NodeRef> {
    let mut in_residual = vec![true; nodes.len()];
    for &i in done {
        in_residual[i] = false;
    }
    let start = (0..nodes.len())
        .filter(|&i| in_residual[i])
        .min_by(|&a, &b| nodes[a].id.cmp(&nodes[b].id))
        .expect("residual is non-empty when a cycle exists");
    let mut path = vec![start];
    loop {
        let cur = *path.last().expect("path never empty");
        let prev = pred[cur]
            .iter()
            .copied()
            .filter(|&p| in_residual[p])
            .min_by(|&a, &b| nodes[a].id.cmp(&nodes[b].id))
            .expect("residual nodes keep a residual predecessor");
        if let Some(hit) = path.iter().position(|&x| x == prev) {
            let mut cycle = vec![prev];
            cycle.extend(path[hit + 1..].iter().rev().copied());
            cycle.push(prev);
            return cycle
                .into_iter()
                .map(|i| NodeRef {
                    id: nodes[i].id.clone(),
                    title: nodes[i].title.clone(),
                })
                .collect();
        }
        path.push(prev);
    }
}

/// Effective-pinned set: `pinned: true` nodes plus the transitive closure
/// of `imports` targets reachable from them — an imported node is always
/// in context even when its own flag is false.
fn effective_pinned(
    nodes: &[NodeIn],
    edges: &[&EdgeIn],
    id_to_idx: &HashMap<&str, usize>,
) -> Vec<bool> {
    let mut imports: Vec<Vec<usize>> = vec![Vec::new(); nodes.len()];
    for e in edges {
        if e.kind == EdgeKindIn::Imports {
            imports[id_to_idx[e.source.as_str()]].push(id_to_idx[e.target.as_str()]);
        }
    }
    let mut set: Vec<bool> = nodes.iter().map(|n| n.pinned).collect();
    let mut queue: Vec<usize> = (0..nodes.len()).filter(|&i| set[i]).collect();
    while let Some(i) = queue.pop() {
        for &t in &imports[i] {
            if !set[t] {
                set[t] = true;
                queue.push(t);
            }
        }
    }
    set
}

/// A condition is a glob iff it has no whitespace and at least one of
/// `*`, `?`, `[`, `/`; otherwise it is natural language.
fn is_glob(condition: &str) -> bool {
    !condition.chars().any(char::is_whitespace)
        && condition.chars().any(|c| matches!(c, '*' | '?' | '[' | '/'))
}

/// A clean folder glob is exactly `<dir>/**` where every `/`-separated
/// segment of `<dir>` is a plain path component: non-empty, not `.` or
/// `..`, and free of glob metacharacters, backslashes, and drive colons
/// (`src/net/**` → `src/net`; `src/net/**/*` is not clean and stays a root
/// bullet). Mirroring the `resolve_within_root` component walk here means a
/// clean dir can never alias another output path (`.` → root, `src/.` →
/// `src`) or escape the root (`../lib`) — dirty dirs simply stay root
/// bullets — and makes `dir.split('/').count()` the true directory depth
/// for the nested-file `../` link prefix.
fn clean_glob_dir(condition: &str) -> Option<&str> {
    let dir = condition.strip_suffix("/**")?;
    let clean = dir.split('/').all(|seg| {
        !seg.is_empty()
            && seg != "."
            && seg != ".."
            && !seg
                .chars()
                .any(|c| matches!(c, '*' | '?' | '[' | ']' | '\\' | ':'))
    });
    clean.then_some(dir)
}

/// Render a string as a YAML scalar for `.mdc` frontmatter. Values that are
/// safe as plain scalars (the common case — keeps output byte-identical to
/// the spec goldens) pass through untouched; anything that would break or
/// change meaning in plain style (`: `, leading indicator chars, newlines,
/// `null`/booleans, number-like strings — titles come from hand-editable
/// graph.json) is emitted as a double-quoted scalar with escapes.
fn yaml_scalar(value: &str) -> String {
    const RESERVED: &[&str] = &[
        "~", "null", "Null", "NULL", "true", "True", "TRUE", "false", "False", "FALSE", "yes",
        "Yes", "YES", "no", "No", "NO", "on", "On", "ON", "off", "Off", "OFF",
    ];
    let plain_safe = !value.is_empty()
        && !RESERVED.contains(&value)
        && !value.starts_with(|c: char| {
            c.is_whitespace() || c.is_ascii_digit() || "-?:,[]{}#&*!|>'\"%@`+.".contains(c)
        })
        && !value.ends_with(|c: char| c.is_whitespace() || c == ':')
        && !value.contains(": ")
        && !value.contains(" #")
        && !value.chars().any(char::is_control);
    if plain_safe {
        return value.to_string();
    }
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// True when one of the first 10 trimmed lines equals the GENERATED header
/// (10 because `.mdc` carries it after the frontmatter).
fn has_header(content: &str) -> bool {
    content.lines().take(10).any(|l| l.trim() == GENERATED_HEADER)
}

/// The shapes compile is allowed to write: exactly `CLAUDE.md`, any path
/// ending in `AGENTS.md`, or one component under `.cursor/rules/` with an
/// `.mdc` extension.
fn is_allowed_output(rel: &str) -> bool {
    let norm = rel.replace('\\', "/");
    let parts: Vec<&str> = norm.split('/').filter(|p| !p.is_empty() && *p != ".").collect();
    match parts.as_slice() {
        [.., "AGENTS.md"] => true,
        ["CLAUDE.md"] => true,
        [".cursor", "rules", name] => name
            .strip_suffix(".mdc")
            .is_some_and(|stem| !stem.is_empty()),
        _ => false,
    }
}

// ── Adapters ──────────────────────────────────────────────────────────

/// Everything the adapters read, built once after validation passes.
struct Ctx<'a> {
    project_name: String,
    nodes: &'a [NodeIn],
    /// Node indices in total order.
    order: Vec<usize>,
    /// node index → rank in `order`.
    pos: Vec<usize>,
    /// Effective-pinned node indices, in total order.
    pinned: Vec<usize>,
    pinned_set: Vec<bool>,
    live_edges: Vec<&'a EdgeIn>,
    id_to_idx: HashMap<&'a str, usize>,
}

impl Ctx<'_> {
    fn node(&self, id: &str) -> &NodeIn {
        &self.nodes[self.id_to_idx[id]]
    }

    /// On-demand bullets from `references` and `conditional` edges, sorted
    /// by (compiled order of the target, edge id).
    fn on_demand_bullets(&self, link: &dyn Fn(&NodeIn) -> String) -> Vec<String> {
        let mut items: Vec<(usize, &str, String)> = Vec::new();
        for e in &self.live_edges {
            let target = self.node(&e.target);
            let text = match e.kind {
                EdgeKindIn::References => {
                    format!(
                        "- When working on **{}**, read {}.",
                        self.node(&e.source).title,
                        link(target)
                    )
                }
                EdgeKindIn::Conditional => {
                    let condition = e.condition.as_deref().unwrap_or("");
                    if is_glob(condition) {
                        format!("- When touching `{condition}`, read {}.", link(target))
                    } else {
                        format!("- When {condition}, read {}.", link(target))
                    }
                }
                _ => continue,
            };
            items.push((self.pos[self.id_to_idx[e.target.as_str()]], e.id.as_str(), text));
        }
        items.sort_by(|a, b| (a.0, a.1).cmp(&(b.0, b.1)));
        items.into_iter().map(|(_, _, text)| text).collect()
    }

    /// Root `CLAUDE.md` (`claude: true`) or root `AGENTS.md` — identical
    /// structure, `@path` imports vs markdown links.
    fn emit_root(&self, claude: bool) -> String {
        let mut lines: Vec<String> = vec![
            GENERATED_HEADER.to_string(),
            String::new(),
            format!("# {} — agent context", self.project_name),
        ];
        if !self.pinned.is_empty() {
            lines.push(String::new());
            lines.push("## Always read".to_string());
            lines.push(String::new());
            for &i in &self.pinned {
                let n = &self.nodes[i];
                lines.push(if claude {
                    format!("@{}", n.file_path)
                } else {
                    format!("- [{}]({})", n.title, n.file_path)
                });
            }
        }
        let bullets = if claude {
            self.on_demand_bullets(&|n: &NodeIn| format!("@{}", n.file_path))
        } else {
            self.on_demand_bullets(&|n: &NodeIn| format!("[{}]({})", n.title, n.file_path))
        };
        if !bullets.is_empty() {
            lines.push(String::new());
            lines.push("## Read when relevant".to_string());
            lines.push(String::new());
            lines.extend(bullets);
        }
        let mut out = lines.join("\n");
        out.push('\n');
        out
    }

    /// One `{dir}/AGENTS.md` per clean-folder-glob conditional, merged per
    /// dir, links prefixed with one `../` per path segment. These are an
    /// addition to the root bullets, not a move.
    fn emit_nested_agents(&self) -> Vec<(String, String)> {
        let mut by_dir: BTreeMap<&str, Vec<&EdgeIn>> = BTreeMap::new();
        for e in &self.live_edges {
            if e.kind != EdgeKindIn::Conditional {
                continue;
            }
            if let Some(dir) = e.condition.as_deref().and_then(clean_glob_dir) {
                by_dir.entry(dir).or_default().push(e);
            }
        }
        by_dir
            .into_iter()
            .map(|(dir, mut edges)| {
                edges.sort_by(|a, b| {
                    (self.pos[self.id_to_idx[a.target.as_str()]], &a.id)
                        .cmp(&(self.pos[self.id_to_idx[b.target.as_str()]], &b.id))
                });
                let prefix = "../".repeat(dir.split('/').count());
                let mut lines: Vec<String> = vec![
                    GENERATED_HEADER.to_string(),
                    String::new(),
                    format!("# {} — context for {}", self.project_name, dir),
                    String::new(),
                ];
                for e in edges {
                    let n = self.node(&e.target);
                    lines.push(format!("- Read [{}]({}{}).", n.title, prefix, n.file_path));
                }
                let mut content = lines.join("\n");
                content.push('\n');
                (format!("{dir}/AGENTS.md"), content)
            })
            .collect()
    }

    /// `.cursor/rules/*.mdc` — one per node in (effective-pinned ∪ targets
    /// of conditional-glob edges), in total order. Pinned wins over globs.
    /// Stale `.mdc` from earlier compiles are not deleted (out of scope for
    /// Phase 2).
    fn emit_cursor(
        &self,
        read_file: &dyn Fn(&str) -> Result<String, String>,
    ) -> Result<Vec<(String, String)>, String> {
        // node index → glob conditions, in edge-id order.
        let mut globs: HashMap<usize, Vec<(&str, &str)>> = HashMap::new();
        for e in &self.live_edges {
            if e.kind != EdgeKindIn::Conditional {
                continue;
            }
            let condition = e.condition.as_deref().unwrap_or("");
            if !is_glob(condition) {
                continue;
            }
            globs
                .entry(self.id_to_idx[e.target.as_str()])
                .or_default()
                .push((e.id.as_str(), condition));
        }
        for list in globs.values_mut() {
            list.sort_by(|a, b| a.0.cmp(b.0));
        }

        let mut stem_counts: HashMap<String, u32> = HashMap::new();
        let mut out = Vec::new();
        for &i in &self.order {
            let n = &self.nodes[i];
            let pinned = self.pinned_set[i];
            let node_globs = globs.get(&i);
            if !pinned && node_globs.is_none() {
                continue;
            }
            let stem = Path::new(&n.file_path)
                .file_stem()
                .map(|s| s.to_string_lossy().to_lowercase())
                .unwrap_or_else(|| n.id.to_lowercase());
            let count = stem_counts
                .entry(stem.clone())
                .and_modify(|c| *c += 1)
                .or_insert(1);
            let name = if *count == 1 {
                stem
            } else {
                format!("{stem}-{count}")
            };
            let rule_line = if pinned {
                "alwaysApply: true".to_string()
            } else {
                let joined = node_globs
                    .expect("non-pinned nodes reach here only as glob targets")
                    .iter()
                    .map(|(_, c)| *c)
                    .collect::<Vec<_>>()
                    .join(",");
                format!("globs: {}", yaml_scalar(&joined))
            };
            let raw = read_file(&n.file_path)?;
            let body = raw.replace("\r\n", "\n").replace('\r', "\n");
            let body = body.trim_end_matches('\n');
            let mut content = format!(
                "---\ndescription: {}\n{}\n---\n{}\n",
                yaml_scalar(&n.title),
                rule_line,
                GENERATED_HEADER
            );
            if !body.is_empty() {
                content.push('\n');
                content.push_str(body);
                content.push('\n');
            }
            out.push((format!(".cursor/rules/{name}.mdc"), content));
        }
        Ok(out)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn temp_project(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("cowtext-compile-{tag}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn touch(path: &Path, content: &str) {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(path, content).unwrap();
    }

    fn node(id: &str, title: &str, file_path: &str, read_order: i64, pinned: bool) -> serde_json::Value {
        json!({
            "id": id, "title": title, "role": "rules", "brief": "",
            "filePath": file_path, "readOrder": read_order, "pinned": pinned,
            "position": { "x": 0, "y": 0 }
        })
    }

    fn edge(id: &str, source: &str, target: &str, kind: &str, condition: Option<&str>) -> serde_json::Value {
        let mut e = json!({ "id": id, "source": source, "target": target, "kind": kind });
        if let Some(c) = condition {
            e["condition"] = json!(c);
        }
        e
    }

    fn graph_json(
        name: &str,
        nodes: &[serde_json::Value],
        edges: &[serde_json::Value],
        targets: &[&str],
    ) -> String {
        json!({
            "version": 1, "projectName": name,
            "nodes": nodes, "edges": edges, "compileTargets": targets
        })
        .to_string()
    }

    fn preview(root: &Path, graph: &str) -> CompilePreview {
        compile_preview(root.to_string_lossy().into_owned(), graph.to_string()).unwrap()
    }

    /// The §1.6 example graph: 2 pinned + 1 references + 1 conditional glob.
    fn golden_graph(targets: &[&str]) -> String {
        graph_json(
            "TestProj",
            &[
                node("a", "Persona", "context/persona.md", 1, true),
                node("b", "Rules", "context/rules.md", 2, true),
                node("c", "Networking notes", "context/net-notes.md", 3, false),
                node("d", "Net rules", "context/net-rules.md", 4, false),
            ],
            &[
                edge("e1", "a", "c", "references", None),
                edge("e2", "a", "d", "conditional", Some("src/net/**")),
            ],
            targets,
        )
    }

    fn golden_files(dir: &Path) {
        touch(&dir.join("context/persona.md"), "persona body\n");
        touch(&dir.join("context/rules.md"), "rules body\n");
        touch(&dir.join("context/net-notes.md"), "notes body\n");
        touch(&dir.join("context/net-rules.md"), "net rules body\n");
    }

    #[test]
    fn cycle_detected_with_path() {
        let dir = temp_project("cycle");
        touch(&dir.join("context/a.md"), "a\n");
        touch(&dir.join("context/b.md"), "b\n");
        let g = graph_json(
            "P",
            &[
                node("a", "A", "context/a.md", 1, true),
                node("b", "B", "context/b.md", 2, true),
            ],
            &[
                edge("e1", "a", "b", "sequence", None),
                edge("e2", "b", "a", "sequence", None),
            ],
            &["claude"],
        );
        let p = preview(&dir, &g);
        assert!(p.files.is_empty());
        assert_eq!(p.errors.len(), 1);
        match &p.errors[0] {
            ValidationError::Cycle { nodes } => {
                assert_eq!(nodes.len(), 3);
                assert_eq!(nodes.first().unwrap().id, nodes.last().unwrap().id);
            }
            other => panic!("expected a cycle error, got {other:?}"),
        }
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn imports_and_sequence_ordering() {
        let dir = temp_project("order");
        for f in ["a", "b", "c"] {
            touch(&dir.join(format!("context/{f}.md")), "x\n");
        }
        // readOrder 3/1/2; imports A→C means C must appear before A.
        let g = graph_json(
            "P",
            &[
                node("a", "A", "context/a.md", 3, true),
                node("b", "B", "context/b.md", 1, true),
                node("c", "C", "context/c.md", 2, true),
            ],
            &[edge("e1", "a", "c", "imports", None)],
            &["claude"],
        );
        let p1 = preview(&dir, &g);
        let p2 = preview(&dir, &g);
        assert!(p1.errors.is_empty());
        let at_lines: Vec<&str> = p1.files[0]
            .new_content
            .lines()
            .filter(|l| l.starts_with('@'))
            .collect();
        assert_eq!(at_lines, ["@context/b.md", "@context/c.md", "@context/a.md"]);
        assert_eq!(p1.files[0].new_content, p2.files[0].new_content);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn read_order_breaks_ties() {
        let dir = temp_project("ties");
        for f in ["a", "b", "c"] {
            touch(&dir.join(format!("context/{f}.md")), "x\n");
        }
        // No edges: pure readOrder; equal readOrder falls back to id order.
        let g = graph_json(
            "P",
            &[
                node("c", "C", "context/c.md", 2, true),
                node("a", "A", "context/a.md", 2, true),
                node("b", "B", "context/b.md", 1, true),
            ],
            &[],
            &["claude"],
        );
        let p = preview(&dir, &g);
        assert!(p.errors.is_empty());
        let at_lines: Vec<&str> = p.files[0]
            .new_content
            .lines()
            .filter(|l| l.starts_with('@'))
            .collect();
        assert_eq!(at_lines, ["@context/b.md", "@context/a.md", "@context/c.md"]);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn missing_file_reported() {
        let dir = temp_project("missing");
        let g = graph_json(
            "P",
            &[node("a", "A", "context/gone.md", 1, true)],
            &[],
            &["claude"],
        );
        let p = preview(&dir, &g);
        assert!(p.files.is_empty());
        assert_eq!(p.errors.len(), 1);
        match &p.errors[0] {
            ValidationError::MissingFile { node_id, file_path, .. } => {
                assert_eq!(node_id, "a");
                assert_eq!(file_path, "context/gone.md");
            }
            other => panic!("expected a missing-file error, got {other:?}"),
        }
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn dangling_edge_reported() {
        let dir = temp_project("dangling");
        touch(&dir.join("context/a.md"), "a\n");
        let g = graph_json(
            "P",
            &[node("a", "A", "context/a.md", 1, true)],
            &[edge("e1", "a", "ghost", "references", None)],
            &["claude"],
        );
        let p = preview(&dir, &g);
        assert!(p.files.is_empty());
        assert_eq!(p.errors.len(), 1);
        match &p.errors[0] {
            ValidationError::DanglingEdge { edge_id, edge_kind, missing_end } => {
                assert_eq!(edge_id, "e1");
                assert_eq!(edge_kind, "references");
                assert_eq!(missing_end, "ghost");
            }
            other => panic!("expected a dangling-edge error, got {other:?}"),
        }
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn golden_claude_output() {
        let dir = temp_project("golden-claude");
        golden_files(&dir);
        let p = preview(&dir, &golden_graph(&["claude"]));
        assert!(p.errors.is_empty());
        assert_eq!(p.files.len(), 1);
        let f = &p.files[0];
        assert_eq!(f.rel_path, "CLAUDE.md");
        assert_eq!(f.target, "claude");
        let golden = format!(
            "{GENERATED_HEADER}\n\
             \n\
             # TestProj — agent context\n\
             \n\
             ## Always read\n\
             \n\
             @context/persona.md\n\
             @context/rules.md\n\
             \n\
             ## Read when relevant\n\
             \n\
             - When working on **Persona**, read @context/net-notes.md.\n\
             - When touching `src/net/**`, read @context/net-rules.md.\n"
        );
        assert_eq!(f.new_content, golden);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn golden_agents_output() {
        let dir = temp_project("golden-agents");
        golden_files(&dir);
        let p = preview(&dir, &golden_graph(&["agents"]));
        assert!(p.errors.is_empty());
        let f = &p.files[0];
        assert_eq!(f.rel_path, "AGENTS.md");
        assert_eq!(f.target, "agents");
        let golden = format!(
            "{GENERATED_HEADER}\n\
             \n\
             # TestProj — agent context\n\
             \n\
             ## Always read\n\
             \n\
             - [Persona](context/persona.md)\n\
             - [Rules](context/rules.md)\n\
             \n\
             ## Read when relevant\n\
             \n\
             - When working on **Persona**, read [Networking notes](context/net-notes.md).\n\
             - When touching `src/net/**`, read [Net rules](context/net-rules.md).\n"
        );
        assert_eq!(f.new_content, golden);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn nested_agents_for_clean_glob() {
        let dir = temp_project("nested");
        golden_files(&dir);
        let g = graph_json(
            "P",
            &[
                node("a", "Persona", "context/persona.md", 1, true),
                node("c", "Networking notes", "context/net-notes.md", 2, false),
                node("d", "Net rules", "context/net-rules.md", 3, false),
            ],
            &[
                edge("e1", "a", "d", "conditional", Some("src/net/**")),
                edge("e2", "a", "c", "conditional", Some("src/io/**/*")),
            ],
            &["agents"],
        );
        let p = preview(&dir, &g);
        assert!(p.errors.is_empty());
        // Root AGENTS.md + one nested file; `src/io/**/*` is not clean.
        assert_eq!(p.files.len(), 2);
        assert!(p.files[0].new_content.contains(
            "- When touching `src/net/**`, read [Net rules](context/net-rules.md)."
        ));
        let nested = &p.files[1];
        assert_eq!(nested.rel_path, "src/net/AGENTS.md");
        assert_eq!(nested.target, "agents");
        let golden = format!(
            "{GENERATED_HEADER}\n\
             \n\
             # P — context for src/net\n\
             \n\
             - Read [Net rules](../../context/net-rules.md).\n"
        );
        assert_eq!(nested.new_content, golden);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn dirty_glob_dirs_stay_root_bullets() {
        let dir = temp_project("dirty-globs");
        golden_files(&dir);
        // Aliasing (`./**`, `src/./**`, `src//**`), escaping (`../lib/**`,
        // `C:/x/**`), and backslash dirs must not spawn nested AGENTS.md —
        // and must not turn the preview into an infrastructure Err.
        let conditions = [
            "./**",
            "../lib/**",
            "src/./**",
            "src//**",
            "C:/x/**",
            "src\\net/**",
        ];
        let edges: Vec<serde_json::Value> = conditions
            .iter()
            .enumerate()
            .map(|(i, c)| edge(&format!("e{i}"), "a", "d", "conditional", Some(c)))
            .collect();
        let g = graph_json(
            "P",
            &[
                node("a", "Persona", "context/persona.md", 1, true),
                node("d", "Net rules", "context/net-rules.md", 2, false),
            ],
            &edges,
            &["agents"],
        );
        let p = preview(&dir, &g);
        assert!(p.errors.is_empty());
        // Root AGENTS.md only — no nested file for any dirty glob.
        assert_eq!(p.files.len(), 1);
        assert_eq!(p.files[0].rel_path, "AGENTS.md");
        for c in conditions {
            assert!(
                p.files[0]
                    .new_content
                    .contains(&format!("- When touching `{c}`,")),
                "missing root bullet for {c}"
            );
        }
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn cursor_frontmatter_escapes_yaml() {
        let dir = temp_project("cursor-yaml");
        touch(&dir.join("context/net.md"), "net body\n");
        touch(&dir.join("context/notes.md"), "notes body\n");
        let g = graph_json(
            "P",
            &[
                node("a", "Networking: overview", "context/net.md", 1, true),
                node("b", "Notes: \"hi\"", "context/notes.md", 2, false),
            ],
            &[edge("e1", "a", "b", "conditional", Some("[ab]/x/**"))],
            &["cursor"],
        );
        let p = preview(&dir, &g);
        assert!(p.errors.is_empty());
        let by_path: HashMap<&str, &PreviewFile> =
            p.files.iter().map(|f| (f.rel_path.as_str(), f)).collect();
        // `: ` in a plain scalar is invalid YAML → double-quoted.
        assert!(by_path[".cursor/rules/net.mdc"]
            .new_content
            .starts_with("---\ndescription: \"Networking: overview\"\nalwaysApply: true\n---\n"));
        // Once quoting triggers, embedded quotes are escaped; leading `[`
        // in a glob would open a flow sequence in plain style → quoted.
        assert!(by_path[".cursor/rules/notes.mdc"].new_content.starts_with(
            "---\ndescription: \"Notes: \\\"hi\\\"\"\nglobs: \"[ab]/x/**\"\n---\n"
        ));
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn yaml_scalar_plain_and_quoted() {
        // Common cases stay plain — output identical to the spec goldens.
        for plain in ["Persona", "Net rules", "src/net/**", "src/a/**,src/b/**"] {
            assert_eq!(yaml_scalar(plain), plain);
        }
        assert_eq!(yaml_scalar(""), "\"\"");
        assert_eq!(yaml_scalar("true"), "\"true\"");
        assert_eq!(yaml_scalar("123"), "\"123\"");
        assert_eq!(yaml_scalar("#leading"), "\"#leading\"");
        assert_eq!(yaml_scalar("trailing:"), "\"trailing:\"");
        assert_eq!(yaml_scalar("a\nb"), "\"a\\nb\"");
        // Interior quotes/backslashes are legal in plain style; they are
        // escaped only when something else forces double-quoting.
        assert_eq!(yaml_scalar("back\\slash"), "back\\slash");
        assert_eq!(yaml_scalar("say \"hi\""), "say \"hi\"");
        assert_eq!(yaml_scalar(": say \"hi\"\\"), "\": say \\\"hi\\\"\\\\\"");
    }

    #[test]
    fn golden_cursor_frontmatter() {
        let dir = temp_project("cursor");
        touch(&dir.join("context/persona.md"), "persona body\n");
        touch(&dir.join("context/net-rules.md"), "net body\n");
        touch(&dir.join("context/mixed.md"), "mixed body\n");
        let g = graph_json(
            "P",
            &[
                node("a", "Persona", "context/persona.md", 1, true),
                node("d", "Net rules", "context/net-rules.md", 2, false),
                node("m", "Mixed", "context/mixed.md", 3, true),
            ],
            &[
                edge("e1", "a", "d", "conditional", Some("src/net/**")),
                edge("e2", "a", "m", "conditional", Some("src/x/**")),
            ],
            &["cursor"],
        );
        let p = preview(&dir, &g);
        assert!(p.errors.is_empty());
        let by_path: HashMap<&str, &PreviewFile> =
            p.files.iter().map(|f| (f.rel_path.as_str(), f)).collect();
        assert_eq!(p.files.len(), 3);
        assert_eq!(
            by_path[".cursor/rules/persona.mdc"].new_content,
            format!(
                "---\ndescription: Persona\nalwaysApply: true\n---\n{GENERATED_HEADER}\n\npersona body\n"
            )
        );
        assert_eq!(
            by_path[".cursor/rules/net-rules.mdc"].new_content,
            format!(
                "---\ndescription: Net rules\nglobs: src/net/**\n---\n{GENERATED_HEADER}\n\nnet body\n"
            )
        );
        // Pinned wins over globs: alwaysApply, no globs line.
        assert_eq!(
            by_path[".cursor/rules/mixed.mdc"].new_content,
            format!(
                "---\ndescription: Mixed\nalwaysApply: true\n---\n{GENERATED_HEADER}\n\nmixed body\n"
            )
        );
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn header_present_in_every_output() {
        let dir = temp_project("headers");
        golden_files(&dir);
        let p = preview(&dir, &golden_graph(&["claude", "agents", "cursor"]));
        assert!(p.errors.is_empty());
        assert!(!p.files.is_empty());
        for f in &p.files {
            assert!(has_header(&f.new_content), "no header in {}", f.rel_path);
            if f.rel_path.ends_with(".md") {
                assert_eq!(
                    f.new_content.lines().next().unwrap(),
                    GENERATED_HEADER,
                    "header not line 1 in {}",
                    f.rel_path
                );
            }
        }
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn handwritten_flag() {
        let dir = temp_project("handwritten");
        touch(&dir.join("context/a.md"), "a\n");
        let g = graph_json(
            "P",
            &[node("a", "A", "context/a.md", 1, true)],
            &[],
            &["claude"],
        );

        // Absent file → not handwritten, no old content.
        let p = preview(&dir, &g);
        let generated = p.files[0].new_content.clone();
        assert!(!p.files[0].handwritten);
        assert!(p.files[0].old_content.is_none());

        // Non-empty file without the header → handwritten.
        touch(&dir.join("CLAUDE.md"), "my hand-rolled notes\n");
        let p = preview(&dir, &g);
        assert!(p.files[0].handwritten);
        assert!(!p.files[0].unchanged);

        // File carrying the header → not handwritten.
        touch(&dir.join("CLAUDE.md"), &format!("{GENERATED_HEADER}\nold compile\n"));
        let p = preview(&dir, &g);
        assert!(!p.files[0].handwritten);

        // Byte-identical file → unchanged.
        touch(&dir.join("CLAUDE.md"), &generated);
        let p = preview(&dir, &g);
        assert!(!p.files[0].handwritten);
        assert!(p.files[0].unchanged);

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn unknown_fields_and_kinds_tolerated() {
        let dir = temp_project("tolerant");
        touch(&dir.join("context/a.md"), "a\n");
        let g = json!({
            "version": 1,
            "projectName": "P",
            "nodes": [{
                "id": "a", "title": "A", "role": "rules", "brief": "",
                "filePath": "context/a.md", "readOrder": 1, "pinned": true,
                "position": { "x": 0, "y": 0 },
                "lastVerified": "2026-08-16",
                "scenePos": { "tx": 1, "ty": 2 },
                "junk": [1, 2, 3]
            }],
            "edges": [{ "id": "e1", "source": "a", "target": "a", "kind": "futurekind" }],
            "compileTargets": ["claude", "windsurf"]
        })
        .to_string();
        let p = preview(&dir, &g);
        assert!(p.errors.is_empty());
        assert_eq!(p.files.len(), 1);
        assert_eq!(p.files[0].rel_path, "CLAUDE.md");
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn compile_write_allowlist() {
        let dir = temp_project("write");
        let root = dir.to_string_lossy().into_owned();
        let ok = format!("{GENERATED_HEADER}\nbody\n");
        let af = |rel: &str, content: &str| ApprovedFile {
            rel_path: rel.to_string(),
            content: content.to_string(),
        };

        for bad in ["src/evil.md", "../CLAUDE.md", ".cursor/rules/a/b.mdc"] {
            assert!(
                compile_write(root.clone(), vec![af(bad, &ok)]).is_err(),
                "should have rejected {bad}"
            );
        }
        assert!(
            compile_write(root.clone(), vec![af("CLAUDE.md", "no header here\n")]).is_err(),
            "should have rejected headerless content"
        );

        let written = compile_write(
            root.clone(),
            vec![
                af("CLAUDE.md", &ok),
                af("src/net/AGENTS.md", &ok),
                af(".cursor/rules/x.mdc", &ok),
            ],
        )
        .unwrap();
        assert_eq!(written, ["CLAUDE.md", "src/net/AGENTS.md", ".cursor/rules/x.mdc"]);
        for rel in &written {
            assert_eq!(fs::read_to_string(dir.join(rel)).unwrap(), ok);
        }
        let _ = fs::remove_dir_all(&dir);
    }
}
